### ISSUE TITLE
Hsize option for playing with CRT TV - NG Core

### ISSUE THREAD

**Issue by steffpga** [MiSTer-devel/NeoGeo_MiSTer#100]
I would like to make a request regarding the NeoGeo core.
I am in contact with many guys who play on mister with NeoGeo core and we all have the same problem, problem that some of us manage to correct via the menu service of our trinitron tv the neogeo has a slightly bastard display ... in 304 or 320 and the display is so too stretched on the Hsize ... I manage to correct this via the service menu or some who have a PVM do it via the knobs but it's tedious...
We want to know if it is possible to create an option in the menu to create this Hsize function (different from the hposition of jotego and mr-x present in their cores for example) which would prevent all players on CRT from tearing their hair out of their hearts neogeo?
Thanks in advance for those play NeoGeo on CRT TV with MiSTer !

**Comment by jotego** [comment]
Note that one inconvenient we have when providing the solution inside the core is that the configuration is saved independently for each MRA file. So even if the same RBF is used, the user has to manually adjust each booted MRA and manually save settings.

A solution in the framework should tackle this problem too and allow the user to define a global H/V position for a given RBF file rather than individually for each MRA file.

**Comment by steffpga** [comment]
Thank you for your feedback jotego!
I think so too!
But the NeoGeo core is particularly affected by this Hsize problem because half of the games are in 304 and the other in 320 even if the display is unique in 320 ...
It is particularly annoying for CRT cathodic users because the life bars on the samurai series for example are not visible in full but many other games are affected ...
Fuurtek, the creator of the core can provide this functionality?

**Comment by steffpga** [comment]
Can a solution be found to incorporate an H / V size into the core? Indeed, this solution seems to be essential to play in perfect conditions!
I think we have to do with the scaler but only sorgelig and furrtek can tell us if it's possible I think.
Thanks for your feedback

**Comment by Saroumane** [comment]
Hello steff, the native analog output of NeoGeo core is indeed flawed (compared to other cores)

But don't despair ! Here is a workaround.
Put this at the end of your Mister.ini and reboot (I insist : at the end of file. Don't waste time like me when I put it before [MiSTer] section...)
```
[NeoGeo]
;direct_video=0
vga_scaler=1
; 320x224 
video_mode=320,20,29,35,224,10,14,16,6400 
vsync_adjust=2
```
