### ISSUE TITLE
Error detecting memory size when bootcore is used

### ISSUE THREAD

**Issue by JakeWorrell** [MiSTer-devel/NeoGeo_MiSTer#101]
I have been struggling for a while with loading larger ROMs due to memory errors, despite having a 128mb RAM board that passes memory tests.

After trying different roms and various other changes, a member of the forum explained that he also had the same issue, when bootcore was used. I was able to make the error go away by rebooting MiSTer in the menu before starting the NeoGeo core.

So, it appears that using bootcore before loading the NeoGeo core causes the RAM to not correctly be detected. A reboot from the menu fixes this as a workaround.

Please see this forum post by artfakt which highlighted the suspected root cause to me, along with a link to the code: https://misterfpga.org/viewtopic.php?p=7111#p7111

**Comment by sorgelig** [comment]
It's not a bug. It's misusing the MiSTer.
MiSTer has to boot into Menu core at start. 
Already explained this many times. Bootcore feature has minimal 2s wait before start the core, so it should work unless you hack it and start the core directly without Menu core.
