### ISSUE TITLE
KOF96 graphical glitch in Osaka stage

### ISSUE THREAD

**Issue by ItsAtomico** [MiSTer-devel/NeoGeo_MiSTer#103]
King Of Fighters '96 (kof96). 
There's a vertical line during the fight intro in the Osaka/Japan stage (Psycho Soldier team):

https://imgur.com/1Z12E1T
https://imgur.com/NfpSYgJ
https://imgur.com/9BlzYGz

Tried HDMI and Analog I/O out,  AES or MVS mode, 304 or 320px resolution. Same behaviour.
Using Unibios 4.0.

Thanks :)

**Comment by furrtek** [comment]
Should be fixed with 77a2a8e516ac75d3afb46d85ce70faa5dcc21a99. Please close issue if confirmed.
Thanks for reporting :)

**Comment by ItsAtomico** [comment]
Fixed :D. 

Thanks furrtek, great work as always!
