### ISSUE TITLE
Aero Fighters 3 drops sound

### ISSUE THREAD

**Issue by tcapetanakis** [MiSTer-devel/NeoGeo_MiSTer#105]
During the boss fight music, sound will sometimes drop out completely. Sound comes back after the developer splash screen plays. Issue is relatively easy to replicate and is on the current release.

**Comment by jotego** [comment]
I am a bit skeptical about this being an issue in JT12. I'd say it's a system level issue so I won't look at it for now and leave this one for the developers of the system modules.

**Comment by M-Walrus** [comment]
Most likely this is a duplicate report of issue #75 

I have copy/pasted the information from this report into a comment on issue #75 so this one can be closed.

**Comment by Short-Timer** [comment]
This issue also happens currently (20200928) and frequently in Aero Fighters 2 in basically the same manner.  Not sure if it is related to a boss fight, however.

**Comment by paulb-nl** [comment]
Is this still happening? I haven't been able to reproduce this.

**Comment by Toryalai1** [comment]
> Is this still happening? I haven't been able to reproduce this.

I was able to reproduce it. After defeating the monkey boss in stage 10

**Comment by sorgelig** [comment]
close as probably fixed.
