### ISSUE TITLE
Shock Troopers Graphics Glitch

### ISSUE THREAD

**Issue by aphexian** [MiSTer-devel/NeoGeo_MiSTer#108]
I've noticed a graphical glitch in Shock Troopers, evident in the attract mode demo when the explosion appears in the top right of the screen:

https://streamable.com/tgkn4c

I am currently using the NeoGeo_20200928.rbf update released today 28th September however the glitch was also present in previous versions. The ROM I am using is from the Darksoft Neo Geo 2020-05-12 pack.

**Comment by mdd45** [comment]
This glitch appears to be the same on my original mvs.

**Comment by aphexian** [comment]
Thanks for checking. The only reference I have is FBNeo which wasn't displaying the glitch.

**Comment by aphexian** [comment]
Closing, as confirmed by mdd45 this is present on real hardware
