### ISSUE TITLE
Metal Slug Graphics Glitch

### ISSUE THREAD

**Issue by aphexian** [MiSTer-devel/NeoGeo_MiSTer#109]
The below video shows a small glitch in the Metal Slug attract mode, if you look just above Metal Slug's barrel as the screen scrolls upwards (in the screen immediately prior to the shell being loaded) you can see a few glitchy lines:

https://streamable.com/qsxxrs

I am currently using the NeoGeo_20200928.rbf update released today 28th September however the glitch was also present in previous versions. The ROM I am using is from the Darksoft Neo Geo 2020-05-12 pack.

**Comment by mdd45** [comment]
This glitch appears to be the same on my original mvs. You can see it also on mame.

**Comment by aphexian** [comment]
Thanks for checking. As with the Shock Troopers glitch, I wasn't seeing it happening in FBNeo.

**Comment by mdd45** [comment]
on fbneo indeed this glitch (and the shock trooper one) is not visible, but on mame, my original mvs board and neo geo core is the same. Maybe this is due to a timing issue fixed in fbneo.

**Comment by aphexian** [comment]
Brilliant, I think we can close this as a non-issue!
