### ISSUE TITLE
Making MAME romsets.xml - Index question

### ISSUE THREAD

**Issue by sc4mp3r** [MiSTer-devel/NeoGeo_MiSTer#112]
How does one identify the "Index" value for each file?

  <file  name="044-p1.p1" type="P"  **index="4"**  offset="0"/>

**Comment by sorgelig** [comment]
I suggest to use this tool to create consolidated ROM where you won't need to use indexes.
https://github.com/aluzed/MiSTer-Neogeo-Rom-Decrypter
