### ISSUE TITLE
LastBlade2/KOF95 randomly crashes..

### ISSUE THREAD

**Issue by rvrodrigues** [MiSTer-devel/NeoGeo_MiSTer#114]
Hello!
With the NeoGeo_20210114 im getting this random [errors](https://drive.google.com/file/d/1mXMFuNS2Rtsk1KpHqNqpwNQZ3-3YuyN9/view?usp=sharing) with Last Blade 2 or [KOF 95](https://drive.google.com/file/d/1X7wG7z03sRdNzZhz5U6gk-4SloejnVzx/view?usp=sharing), no matter is playing or in attract mode.. randomly happens after 3 or 5 minutes... Already tried 2 sets of differents roms"@MiSTer Pack Add-on - NEOGEO 2020-05-12 or DarksoftRomSet " roms stored in sdcard or in external hdd happens the same... my SDRAM is 128mb from a official seller(ZeroHimself).

**Comment by rvrodrigues** [comment]
My [memtest results](https://drive.google.com/file/d/1MmNR27RVSvO7wscafqH6ks8Zm-bgbNp5/view?usp=drivesdk), also randomly the core reboots itself

**Comment by advert665** [comment]
I got this same error when I changed my ini file with alternate video settings while the rom was loaded, it required reloading the rom to fix. Not your issue, but thought I'd add incase it helps with debugging.

**Comment by rvrodrigues** [comment]
I did changed the sdram and works fine now, bought mine in mids 2019, only using stock power supply... think is like jotego said that because of the voltage problems could put unintend load on the components dimishing their life span
