### ISSUE TITLE
Left-most vertical line in 320 res games blacked out:

### ISSUE THREAD

**Issue by Firebrandx** [MiSTer-devel/NeoGeo_MiSTer#118]
I happened to notice the left-most vertical line of graphics is blacked out on 320-res games. Appears to not matter what game it is. I checked on my AES console and it shows all 320 lines, so this has to be a core bug.

**Comment by sorgelig** [comment]
on which game you test it?

**Comment by Firebrandx** [comment]
Fatal Fury Special, Fatal Fury, Magician Lord. It appears to not matter what game it is. If it's a 320 game, the first vertical line on the left is black, so you end up seeing 319x224.

**Comment by SegaSnatcher** [comment]
I know this is a dumb question, but you have 320 mode enabled in the OSD correct?  Because there is also a 304px mode in the OSD that might be turned on by default.

**Comment by Firebrandx** [comment]
Yes I can EASILY tell the difference between 304 and 320. I used my E1S card to count the pixels anyway.

**Comment by sorgelig** [comment]
I'm already not sure what do you mean.. Is there something on screen where you can clearly see the left most column is missing? Of you just look at some tool?
USB console debug log shows the video has 320 pixels.

**Comment by Firebrandx** [comment]
Look, it's real simple: The left vertical line is blacked out. It may show up in logs, but it's physically blacked out on actual viewing. Do I need to make some screenshots to prove it?

**Comment by Firebrandx** [comment]
Here are direct captures of the 319x224 bug versus correct 320x224:

http://www.firebrandx.com/downloads/proof/MiSTer_Neo_Geo_319_Bug.png

http://www.firebrandx.com/downloads/proof/Neo_Geo_320.png

As you can see, the left-most vertical line is missing (likely just colored black on the footprint of 1920x1080).

**Comment by SegaSnatcher** [comment]
It looks like the Neo-Geo core is shifted to the left and is likely why there is a missing line.  Good catch.

**Comment by Kitrinx** [comment]
I've double checked, left most column is definitely missing for 320 wide games.

**Comment by sorgelig** [comment]
i will check if i can fix it.

**Comment by sorgelig** [comment]
[NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/5984120/NeoGeo.zip)
try this build

**Comment by Firebrandx** [comment]
New build works great! All 320 lines show up properly now. Thanks!
