### ISSUE TITLE
Shocktroopers 2 

### ISSUE THREAD

**Issue by tonysvo614** [MiSTer-devel/NeoGeo_MiSTer#119]
Shick troopers 2 2nd squadron is laggy .....only neo geo that lags slowdowns.

**Comment by felleg** [comment]
You need to be more specific. Do you have video of this? Better yet, can you compare in a video both the original console and the MiSTer core?

**Comment by Toryalai1** [comment]
This is a weird ticket. As felleg mentioned, it is better to have video comparison
