### ISSUE TITLE
Detection problems arcade and console mode

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/NeoGeo_MiSTer#12]
Create an Arcade (MVS) config and save settings.
Reload the core or start power cycled.

Load a game. (Neo Bomberman, Metal Slug, ...) with 9 out of 10 atempts it's in console mode. Even changing to console -> reset & apply and switching back to arcade -> reset and apply (mostly) doesn't help.

There seems to be some problems with the initialization.
If you have a console default setting, load the core and then switch to arcade it mostly works.

Unibios 3.3

**Comment by sorgelig** [comment]
Use console mode in OSD settings and then you can select required mode in unibios and save.
This is how it's supposed to work.

**Comment by PhantombrainM** [comment]
Unibios.fr tells its for MVS, AES and CD-Systems. Also arcade OSD Settings have dip switches which are not available in console mode.

Haven't tried Unibios region settings for a month. But when I did it was not saved and also not consistent. I'll give it another try. 

But I checked original Neo Geo bios too which also sometimes not initialize on Arcade (MVS) mode.
