### ISSUE TITLE
Graffic glich message intro Burning Fight

### ISSUE THREAD

**Issue by gabytomas** [MiSTer-devel/NeoGeo_MiSTer#123]
When starts game there is a graffic glich in the intro.

**Comment by paulb-nl** [comment]
I can't find any glitch

**Comment by steffpga** [comment]
any glitch in last version

**Comment by Toryalai1** [comment]
I can’t find any glitches either. This ticket can be closed

**Comment by gabytomas** [comment]
Ok, thanks. If i find more i open another. Thanks.El 8 ene 2023 20:22, Toy-a ***@***.***> escribió:

I can’t find any glitches either. This ticket can be closed

**Comment by Toryalai1** [comment]
Please close this ticket

**Comment by Toryalai1** [comment]
This ticket can be closed
