### ISSUE TITLE
Missing sound by setting AES or MVS in Unibios

### ISSUE THREAD

**Issue by neogeo81** [MiSTer-devel/NeoGeo_MiSTer#124]
There is a part in the wiki that is wrong:
To simplify things, it is suggested to stick to one system type on the OSD and use uni-bios to change the system type, so that game information is saved consistently.

You can not set it in OSD to Arcade MVS and switch in Unibios to Console or vis-versa because if the system set in OSD does not match the settings in Unibios you will get no sound on certain things that arent on either of the systems. Example KoF98; the arcade version does not have the Neo Geo jingle at the beginning if you set the OSD system to Arcade and the Unibios to Console you will hear nothing.

**Comment by sorgelig** [comment]
Right. UniBIOS makes "soft" conversion with its quirks which is more useful on real hardware than on MiSTer where you can quickly switch between AES and MVS.

**Comment by sorgelig** [comment]
removed that part from ReadMe
