### ISSUE TITLE
Missing Directory: NEOGEO

### ISSUE THREAD

**Issue by evil666** [MiSTer-devel/NeoGeo_MiSTer#125]
Not sure if this is a bug or by design but can you confirm that your core can load games from USB. Currently using the USB version of update_all. All necessary files are located on the USB instead of on the SD card. All games are in their proper directory and sorted subfolders /media/usb0/games/NeoGeo/romsubfolderhere.

I wasn't sure if your core is configured to find games on usb0 like other cores are.

All necessary bios files and usual rom paks have been tried. However when selecting rom file... no dice.

**Comment by evil666** [comment]
Update:
Your documentation states the following:

Copy the NeoGeo_*.rbf file to the 'Console' or 'Arcade' folder (your choice) on the SD card. ROMS should go in the 'games\NeoGeo' folder. 


However the folder needs to be in all caps for it to show for some reason 'games\NEOGEO'

Not sure if you want to update your documentation or change some code.... documentation might be easier.

**Comment by sorgelig** [comment]
MiSTer uses exFAT/FAT32 as main file system which is case insensitive. If you use other file system then compatibility may break due to case sensitivity.

**Comment by evil666** [comment]
The USB Drive is NTFS that I am using however you're absolutely right about case sensitive. And since it is, the documentation should be updated.

**Comment by sromeroi** [comment]
Hi, just a comment about this.

The README file states: `ROMS should go in the 'games\NeoGeo' folder.`

But the CONF_STR in the core sources say:

```
localparam CONF_STR = {
  "NEOGEO;;",
```

People using exFAT/FAT32 won't notice the difference but in my case I'm using an EXT4 external drive and the NeoGeo core was not able to find my roms until y renamed the folder from NeoGeo to NEOGEO.

So maybe the README file should be change to refer to the folder as games\NEOGEO. 

Thanks.

**Comment by sorgelig** [comment]
I think, it's better to mount your drive with case insensitive mode. While in this particular case it will be ok to use NEOGEO name, it may happen in some scripts it can be called as NeoGeo. Thus it's highly recommended to use either case insensitive file system OR mount accordingly.
