### ISSUE TITLE
Cannot load Magical Drop III from USB0 Harddisk

### ISSUE THREAD

**Issue by evidencedj** [MiSTer-devel/NeoGeo_MiSTer#126]
Hi,

I am not able to load the game Magical Drop III from my 2TB USB drive. It's a WD Black HDD.
When I load the rom the MiSTer freezes completely while loading. All other games on NeoGeo load fine. I can only shut the MiSTer down afterwards. When I copy the rom to the SD card. It loads just fine. My cousin has the same problem with Magical Drop III and his USB Harddisk. My SD-Card and USB drive are formatted as exFat.

Maybe I am doing something wrong. 

Best regards

**Comment by sorgelig** [comment]
check USB console messages. May be you will find the difference there.
Possibly file names case sensitivity problem.

**Comment by evidencedj** [comment]
Thank you for the fast response. Can you point me in the right direction? I checked /var/log/messages and dmesg with no info on the file access. Is there a special place to look?

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/wiki/Console-connection

**Comment by Toryalai1** [comment]
This issue can be closed as it is not a core bug
