### ISSUE TITLE
32MB VROM doesn't work

### ISSUE THREAD

**Issue by matt456** [MiSTer-devel/NeoGeo_MiSTer#128]
YM2610 32MB bank test doesn't play the 2nd BANK correctly like on real hardware:

Details and original ROM available here
[YM2610 NoPCM 32MB](https://blastar.citavia.de/index.php?controller=post&action=view&id_post=42)
from
[Original discussion](https://www.yaronet.com/topics/188955-ngfx-soundbuilder/2#post-32)

Attached is a Mister compatible romset
[ngym2610.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/6433416/ngym2610.zip)

**Comment by sorgelig** [comment]
there are many NeoGeo 32MB games - they work.
So it's just ROM not correctly combined

**Comment by matt456** [comment]
Sorry, I should have been clearer it is not the romset that is 32MB but the
VROM itself that is 32MB within the romset.

The YM2610 has an addressable range allowing VROM to be larger than 16MB,
more recent indie/homebrew games are able to take advantage of the larger
size.

This test romset executes perfectly on real hardware.

**Comment by jotego** [comment]
If my notes are correct, the YM2610 had a 24-bit bus for the ADPCM B channel. The chip itself had 12 pins on which the address was outputted in two steps, requiring an external latch.
That's only 16MB. Maybe there was a latch external to the YM2610 used to select different ROM banks. 
I made the YM2610 work on the JT12 module 2 years ago, so my memory is a bit blurry.

**Comment by jotego** [comment]
Sorry, after visiting the URL you referenced I see that they refer to 16MB+16MB, A channels plus B channel. That should work in JT10 (YM2610 flavor of JT12) ok. 
There could be a system level limitation in the core.

**Comment by sorgelig** [comment]
Real hardware has 2 parts: console and cart. Core has to emulate not only console but cart internals as well. If i understood right, there are no games using this config, so it's one and only cart has such hardware, and this is not a game. So it's just this exact cart config is not emulated by core.

**Comment by matt456** [comment]
Sure, I don't know the internals of your core well enough to know where
things divide. I'm just reporting a configuration that is technically valid
by the original console in case you had a logical behaviour that needed a
slight tweak.

For what it's worth this configuration will feature in the game Xeno Crisis
for Neo Geo on AES/MVS and in any future games we develop.

**Comment by jotego** [comment]
Does this cartridge use additional hardware to pull this trick? As Sorgelig says, cartridges can include additional devices (pretty much anything). Do you know, Matt, if something like that could be happening?

**Comment by matt456** [comment]
Hi Jose, there are no extra tricks on the PCB to achieve it. If you set it
up as 16MB A + 16MB B, this is possible with standard HW.

FYI - I'm one of the main developers who created Xeno Crisis.

**Comment by sorgelig** [comment]
Core actually supports 16MB A + 16MB B when ROM has no pcm flag set.
I need to remember right rom file set for such config.
probably it must be vroma0 16MB and vromb0 16MB

**Comment by matt456** [comment]
Great, thank you Alexey I'll have a try with that, thank you!

**Comment by sorgelig** [comment]
here is corrected one (includes correct romset info):
[ngym2610_ok.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/6446215/ngym2610_ok.zip)
Just copy it into games/NeoGeo - you will see "NGYM Corrected" name in list.

**Comment by matt456** [comment]
Thanks that works a treat and XenoCrisis with the same settings is also
working. Appreciate you taking the time to look at this.

Cheers,
Matt

**Comment by sorgelig** [comment]
good!
