### ISSUE TITLE
No Sound When trying to play any Neo Geo games.

### ISSUE THREAD

**Issue by mawk** [MiSTer-devel/NeoGeo_MiSTer#130]
I've been having this issue since getting my MiSTer set up the other week. Most cores that I've set up work just fine and output audio properly. However, I'm not getting any audio from the Neo Geo core (on any game). I've tested this with both HDMI and optical out, and neither output is giving me anything.

I'm sure this isn't enough information to go off of here, so let me know what other info you'd like me to provide. Thanks!

**Comment by sorgelig** [comment]
Please go to MiSTer forum for discussion about setup problems. It seems something related to your specific setup.

**Comment by mawk** [comment]
Ah, my bad. Will do.

**Comment by mawk** [comment]
I've done a bit more digging since the other night, and I found that I was able to get audio on the Neo Geo core simply by reverting to most prior versions. I just tested releases:
20200820
20200928
20210114
20210210
20210222
20210225

And I found that the only release where I'm not getting audio is the most recent one: 20210225.

Let me know if you'd like me to re-close this issue, as it's clearly something hitting my configuration (for whatever reason), but I wanted to bring your attention to it since it seems to be an issue that has arisen with the latest Neo Geo release.

**Comment by Dubon77** [comment]
Have you tried the latest release?

**Comment by jegayon** [comment]
> 
> 
> I've done a bit more digging since the other night, and I found that I was able to get audio on the Neo Geo core simply by reverting to most prior versions. I just tested releases: 20200820 20200928 20210114 20210210 20210222 20210225
> 
> And I found that the only release where I'm not getting audio is the most recent one: 20210225.
> 
> Let me know if you'd like me to re-close this issue, as it's clearly something hitting my configuration (for whatever reason), but I wanted to bring your attention to it since it seems to be an issue that has arisen with the latest Neo Geo release.

Try with the last core (any core) to reload it once you have it loaded. Maybe it will work for you. Sorry for my English.

**Comment by Toryalai1** [comment]
Its probably your setup. This issue can be closed
