### ISSUE TITLE
Hanging notes in Aero Fighters 2

### ISSUE THREAD

**Issue by tenshin2002** [MiSTer-devel/NeoGeo_MiSTer#131]
Playing Aero Fighters 2 for some time it reaches a point where the sound crashes and you get "hanging notes". You can continue to play the game but the sound is "stuck". This seems to happen randomly but it takes some time playing before it happens, most times it happens about the time it takes to reach the Monkey boss fight. But sometimes earlier than that.
I have the .neo romset and Unibios 4. I tried with original bios as well and the issue remains. I set the core to MVS NTSC and Europe Arcade in unibios.

**Comment by theypsilon** [comment]
I reported this one here too: https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/75#issuecomment-625425467

**Comment by yavimaya** [comment]
Still happening on NeoGeo_20220403

**Comment by Toryalai1** [comment]
This still seems to happen with the latest unstable from @paulb-nl.

**Comment by Toryalai1** [comment]
I cannot reproduce it. I tried with darksoft rom and .neo rom. Other users on the mister discord has confirmed this as well. This ticket can be closed
