### ISSUE TITLE
Question: Will Neo Geo core support SNAC?

### ISSUE THREAD

**Issue by undeadindustries** [MiSTer-devel/NeoGeo_MiSTer#139]
Sorry, I googled around and all the answers I saw were over a year old.

Does or will Neo Geo support SNAC?

Feel free to close this "issue" when answering.

Thanks!

**Comment by Dubon77** [comment]
Neo geo controller uses a pin for each direction and button totalling 10 pins + gnd+vcc,  witch is more then whats available to the official snac. So it isnt possible. This would have been a more apropriate question for the forum and isnt an issue with the core, so please close this issue

**Comment by undeadindustries** [comment]
Thanks for the response!
