### ISSUE TITLE
New feature request to parse the XML

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/NeoGeo_MiSTer#14]
Hi
its possible to have relative paths for each file in the xml (instead only the name file inside the folder like now)? example: <file name="../002-pg.p1" />
I explain:
one zip file in hbmame has many versions inside (its a merged set that I use). The common files are in the root of the zip and each subfolder has only the files changed for that version. 
One game that has a zip of 1GB (like kof987) and hundreds of versions, if we decompress all the files for all the versions we get something like 36GB (can't remember the right size but its something like this).
Thanks

**Comment by jotego** [comment]
I would add to that the ability to uncompress, at least using the gzip
format. So each file can be individually compressed to save space without
requiring much memory to uncompress. It is ok to assume that SD cards have
infinite capacity when you work with 8 bit systems but NeoGeo and other
future cores are still challenging to SD cards.

**Comment by sorgelig** [comment]
I think should be no problem to add relative paths to filenames.

> I would add to that the ability to uncompress, at least using the gzip format.

zip is already supported long time.

**Comment by jotego** [comment]
So can we refer to zip files from within the XML?

**Comment by sorgelig** [comment]
probably.. i didn't try yet.
There are about only ~250 games for NeoGeo. And there is no much point to zip them. They are pretty fine in unpacked form. It's not like thousands NES games.

**Comment by eubrunosilva** [comment]
mister should see the zip like a folder and maybe open the files inside... 
i also can try with hbmame... because here could be cool to use zip.. just copy the zip to a folder and it will run (after its possible to give relative path to files in xml :) )

**Comment by eubrunosilva** [comment]
Hi
so here you can download a xml to hbmame kof96 from hbmame 0.213 (if needed i can send a pm with this zip file): https://mega.nz/#!mB1RUSrR!uKcMF2WghQwr0LSUC4KNjHRUdDdM8wmAtysZ1a3w0IM

giving the game kof96ae1 as an example:
game can have files in that set folder (214lx.p1)
game can have files in the folder before (../214.c3)
games can have files in other folders (../kof96ae/214ae.c7)

so its really needed for core/mister to follow the relative path of the file

Thanks

**Comment by eubrunosilva** [comment]
Hi
i think this issue should be on main_mister?
do you want me to open this there and close this one?

**Comment by sorgelig** [comment]
i've just pushed the commit fixing the relative paths.
If there are further issues with this, then open a new issue in Main.

**Comment by eubrunosilva** [comment]
just to say that... it works :)
thanks
