### ISSUE TITLE
There is a graphic problem with kof 2003

### ISSUE THREAD

**Issue by okami2012** [MiSTer-devel/NeoGeo_MiSTer#140]
![3818a6d7ee5eef70c9ce9ef4a2a9bf3](https://user-images.githubusercontent.com/20699635/133886893-56092830-1606-441e-84ce-74f914391bf3.jpg)

**Comment by Toryalai1** [comment]
This is fixed with the pull request from paulb-nl: https://github.com/MiSTer-devel/NeoGeo_MiSTer/pull/172

**Comment by paulb-nl** [comment]
Fixed in release 20221224
