### ISSUE TITLE
UniBIOS 4.0 splash screen behaves erratically, depending on unexpected factors

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/NeoGeo_MiSTer#145]
This might be a bug with the UniBIOS rather than this core, but I can't tell which.

Apparently there are two dumps of the `sfix` BIOS ROM floating around:

1. `sfix.sfx` - bad dump used by MAME 0.127 and earlier  (md5: `eba274d931f630efbbf723c19fcd8744`)
2. `sfix.sfix` (notice the differently-spelled extension) - redump used by MAME 0.128 and later (md5: `aa2b5d0eae4158ffc0d7d63481c7830b`)

When using dump `#1` renamed to `sfix.sfix` with the latest MiSTer NeoGeo core and UniBIOS 4.0, the UniBIOS appears to work correctly: after loading the core and a game ROM, when the UniBIOS splash screen shows, the user can press ABC buttons simultaneously to enter the UniBIOS settings page.

But when using dump `#2` (which is the one pulled down by the BIOS updater script), the UniBIOS behaves erratically: after loading the core and a game ROM, pressing ABC buttons simultaneously during the UniBIOS splash screen does _not_ enter the UniBIOS settings page.  To get it to work, the user must press SELECT+START after the game boots to get into the UniBIOS in-game menu, then choose to soft reset... and then on the subsequent restart, pressing ABC on the UniBIOS splash screen finally works.  This workaround sticks until the core is unloaded or the system is reset.  The next time the core is loaded, the same workaround must be performed again.

**Comment by c0d3h4x0r** [comment]
More strange findings:

- If I use the good dump (`#1`) with any earlier UniBIOS version, the UniBIOS splash screen doesn't show up at all.
- If I use the good dump (`#1`) with UniBIOS 4.0, the UniBIOS splash screen appears, but:
  - If I use the default core setting `Input: Joystick or Spinner`, then pressing ABC buttons at the UniBIOS splash screen does nothing.
  - If I change to the core setting `Input: Joystick` (no spinner), then pressing ABC buttons at the UniBIOS splash screen works as expected.

**Comment by sorgelig** [comment]
Because of how spinner on NeoGeo works it may hold several buttons/directions in some positions even actual spinner isn't connected. So better to keep spinner option disabled by default.

**Comment by synrais** [comment]
I found that if you set the service dip on, load into service then exit, turn dip off, you can now A+B+C to enter the splash.

**Comment by sorgelig** [comment]
Should be UniBIOS issue
