### ISSUE TITLE
Horrendous flickering in Metal Slug 3

### ISSUE THREAD

**Issue by Missingno255** [MiSTer-devel/NeoGeo_MiSTer#153]
There is really bad flickering lines of garbage at the top of the screen in Metal Slug 3, through out the course of the game. In the Final Mission, when fighting the alien mothership (after the rocket launch, but before entering the ship), one of the sprites that connects to it starts flickering really badly when being shot at, like on the NES/Famicom. It's always reproduceable.

**Comment by Real-Dampfwalze** [comment]
If it's lines of pixels you are talking of, then it is exactly like on the real hardware. I got Metal Slug 3 for AES and MVS and on both hardware there are parts in the game where there are pixel-lines on the top of the screen (where the score etc. is located).
Especially bad is the hidden path in the third level where you can ride the ostrich.
I'm thinking of doing a video comparision, because it actually is a good example to show how exact the MiSTer core replicates the real hardware, while even the Hamster Arcade Archives version doesn't emulate this "errors".

**Comment by Missingno255** [comment]
> If it's lines of pixels you are talking of, then it is exactly like on the real hardware. I got Metal Slug 3 for AES and MVS and on both hardware there are parts in the game where there are pixel-lines on the top of the screen (where the score etc. is located). Especially bad is the hidden path in the third level where you can ride the ostrich. I'm thinking of doing a video comparision, because it actually is a good example to show how exact the MiSTer core replicates the real hardware, while even the Hamster Arcade Archives version doesn't emulate this "errors".

What about the flickering of the mothership? It was flickering horribly like on an NES.

**Comment by Real-Dampfwalze** [comment]
> What about the flickering of the mothership? It was flickering horribly like on an NES.

I can't remember strong flickering in Metal Slug 3. This could be an actual issue. Can you point at what time stamp in this video it is (or would be if it was on the MiSTer) happening? I would then check and compare it on real hardware.
[MS3 Playthrough](https://youtu.be/-m83vMugiWY)

**Comment by Missingno255** [comment]
> > What about the flickering of the mothership? It was flickering horribly like on an NES.
> 
> I can't remember strong flickering in Metal Slug 3. This could be an actual issue. Can you point at what time stamp in this video it is (or would be if it was on the MiSTer) happening? I would then check and compare it on real hardware. [MS3 Playthrough](https://youtu.be/-m83vMugiWY)

31:00 in is where you would see it start to flicker on MiSTer. I don't have real hardware to compare to as an AES/NeoSD are far too expensive and I don't have access to an MVS.

**Comment by Real-Dampfwalze** [comment]
> 31:00 in is where you would see it start to flicker on MiSTer. I don't have real hardware to compare to as an AES/NeoSD are far too expensive and I don't have access to an MVS.

OK. I played the game often enough on the NeoGeo to remember this part well and I am sure there is no flicker of the mother ship on real hardware.

**Comment by paulb-nl** [comment]
I found a video on YouTube which is captured from Neogeo MVS hardware.
https://youtu.be/E-mfy_ZljSo?t=2602

There is loads of flickering there so this seems to be accurate to hardware.
