### ISSUE TITLE
Is it possible to add button macros?

### ISSUE THREAD

**Issue by sugarbear4d4** [MiSTer-devel/NeoGeo_MiSTer#155]
Hello. I run tournaments for Samurai Shodown V Special. I am wanting to move the offline competitive format to MISTer, but a lot players have gotten used to modern conveniences such as button macros. Is it possible to add button macros to this core? 5SP in particular is very heavy on button combinations (A + B, B + C, C + D, A + B + C, B + C + D). 

Thank you

**Comment by sorgelig** [comment]
There is no such functionality in MiSTer. May be if you will find a controller supporting macros internally then it will be possible.

**Comment by sorgelig** [comment]
It is technically hard to implement in either framework or core. It will require some extensive manager with dialogs.
