### ISSUE TITLE
Graphical glitches with March 26 core

### ISSUE THREAD

**Issue by neodivad** [MiSTer-devel/NeoGeo_MiSTer#162]
I updated the Neo Geo core to the latest March 26 version and I've been experiencing some graphical glitches in every game I've tried. Whether I get the core through the update all script or downloading it from GitHub I encounter the same issue. I haven't noticed any issues with any other recently updated cores (NES, Genesis, etc). I haven't made any changes to my settings. The previous Neo Geo cores worked without issue and I've reverted to using the February 12 version.

Is anybody else experiencing these graphical glitches? Any ideas what it could be and how to resolve it? I'm using the DE10 Nano with the USB hub, analog I/O, and 128 MB RAM that I got from MiSTerAddons.com.

![IMG_7612](https://user-images.githubusercontent.com/102765733/161147500-39fdf6e8-3cef-4b51-a53f-746c7d64bebc.JPG)
![IMG_7609](https://user-images.githubusercontent.com/102765733/161147536-0796ce0a-252a-46c5-a88f-c10809ca3adf.JPG)
![IMG_7613](https://user-images.githubusercontent.com/102765733/161147544-b63f511d-ad72-462d-95ba-58b890c8dc4e.JPG)
![IMG_7616](https://user-images.githubusercontent.com/102765733/161147557-6a371919-ae76-4066-9e7b-ce3b57323b53.JPG)
![IMG_7618](https://user-images.githubusercontent.com/102765733/161147570-5e33d032-da90-4bf4-b8fc-56140ea2240f.JPG)

**Comment by birdybro** [comment]
Have you already tried going into the OSD in the core, pressing "Reset Settings", and then resetting the MiSTer and trying again?

The only changes were pretty minor between this and the previous version, almost entirely framework based.

**Comment by birdybro** [comment]
I'm not seeing the same issues you have shown in super baseball 2020. Have you tried a different hdmi cable? When you reset the mister did you fully power it off or just use the menu to reset? The neo geo core sometimes persists the memory from time to time. Let me see...

Can you check your neogeo games folder? Does it have `neo-epo.sp1-AES_BIOS` and `sp-s2.sp1-MVS_BIOS` in it, or are they named `sp-s2.sp1` and `neo-epo.sp1` respectively instead?

**Comment by mt32pi** [comment]
same error, me too
I tested the attached file, but the same error.

**Comment by birdybro** [comment]
Okay, thanks for trying that. Was just making sure the release file is the same as what would compile pretty much. Wipe your config file for the core --> `media/fat/NEOGEO.CFG`. And delete your bios files and redownload them all and place them in there.

**Comment by Noteuveilaibeule** [comment]
Graphical issues here too with the March 26th core. Everything works perfectly well with the previous version.

![IMG_0298 - Copie](https://user-images.githubusercontent.com/102813802/161284751-be7eeb69-ae94-4ede-a10c-2812f90ad2b5.JPEG)
![IMG_0299 - Copie](https://user-images.githubusercontent.com/102813802/161284759-b8e90f36-826a-4e45-b7f0-e6782056d906.JPEG)
![IMG_0300 - Copie](https://user-images.githubusercontent.com/102813802/161284766-9d13f739-0d38-4183-beb5-fc81354d9803.JPEG)

**Comment by jheiger** [comment]
I have having similar issues as the OP. I am using Mistercade.

**Comment by birdybro** [comment]
What romset are you using?

**Comment by jheiger** [comment]
using the Darksoft romset

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/NeoGeo_MiSTer/blob/master/releases/romsets.xml

did you update your romsets.xml?

**Comment by birdybro** [comment]
Yup, looks like theypsilon just updated it 5 hours ago

https://github.com/MiSTer-devel/Distribution_MiSTer/blob/main/games/NEOGEO/romsets.xml

Run the updater again.

**Comment by jheiger** [comment]
changed my roms to the terra onion set and re-ran the update all. still exhibiting the same graphical issues

**Comment by neodivad** [comment]
> I'm not seeing the same issues you have shown in super baseball 2020. Have you tried a different hdmi cable? When you reset the mister did you fully power it off or just use the menu to reset? The neo geo core sometimes persists the memory from time to time. Let me see...
> 
> Can you check your neogeo games folder? Does it have `neo-epo.sp1-AES_BIOS` and `sp-s2.sp1-MVS_BIOS` in it, or are they named `sp-s2.sp1` and `neo-epo.sp1` respectively instead?
> 
> Also try this core and see if it alleviates the issue for you:
> 
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/8394637/NeoGeo.zip)
> 
> I want to see if this made a difference.

I have the same problems with this core.

I experience issues whether I reboot through the menu or power it off and on with the switch on the power cable. 

I have sp-s2.sp1 and neo-epo.sp1 in the neogeo games folder. I've deleted them and downloaded them again through the update all script. I also deleted, downloaded, and added the newest .xml files.

I'm still experiencing the same graphical issues with the latest version while the previous one runs fine.

I'm using the romset with .neo file extensions I got from the Everdrive packs on archive.org a couple of years ago.

**Comment by birdybro** [comment]
What is your vsync_adjust setting set to for this core?

**Comment by neodivad** [comment]
> What is your vsync_adjust setting set to for this core?

I've set vsync_adjust to 1 Match core frequency, 0 Match display frequency, and 2 low lag in the ini settings. I have the same issues regardless of the setting.

**Comment by pplatoon** [comment]
I'm almost 99% sure you used update/all to update. This script has generated many errors for me lately, for example in ao486 it left me without sound and it crashed when trying to download a rom that failed, generating errors in the sd. Perhaps the problem comes from the fact that the files have not been downloaded correctly through this update/all . This script is unpredictable, it may work or it may end up breaking everything. if you update manual everything should go well

**Comment by 8bits4ever** [comment]
Exact the same behaviour here. Rolling back to 20220212 core fixes the issues.

**Comment by birdybro** [comment]
> I'm almost 99% sure you used update/all to update. This script has generated many errors for me lately, for example in ao486 it left me without sound and it crashed when trying to download a rom that failed, generating errors in the sd. Perhaps the problem comes from the fact that the files have not been downloaded correctly through this update/all . This script is unpredictable, it may work or it may end up breaking everything. if you update manual everything should go well

I've been using update all for over a year, it works fine. For the download of the cores themselves it doesn't do anything different, it just calls the official updater.

**Comment by jheiger** [comment]
I reverted to the previous core and the issues are now gone

**Comment by mt32pi** [comment]
neogeo_LLAPI 20220402 core, no problem.

https://github.com/MiSTer-LLAPI/NeoGeo_MiSTer/blob/master/releases/NeoGeo_LLAPI_20220402.rbf

**Comment by 8bits4ever** [comment]
> neogeo_LLAPI 20220402 core, no problem.
> 
> https://github.com/MiSTer-LLAPI/NeoGeo_MiSTer/blob/master/releases/NeoGeo_LLAPI_20220402.rbf

I can confirm this release works perfectly

**Comment by Kitrinx** [comment]
this just really seems to confirm that the build stability is marginal with the framework updates, and some de10's are on the wrong side of it. Make sure you have adequate cooling (heatsink + fan), are not overclocking the HPS, and probably more work needs to be done on the scaler to return it to a less demanding state.

**Comment by sorgelig** [comment]
try this build:
[NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/8403452/NeoGeo.zip)

**Comment by mt32pi** [comment]
> 

this build is no problem. good!

**Comment by neodivad** [comment]
I don't have any problems with this build.

**Comment by birdybro** [comment]
I tested for any regressions on the side of systems that are working (like mine) and don't see anything. Super Baseball 2020 was having a very slight glitch on the top right in the overscan area with the latest release, but that was happening in the previous release too... That is gone with this build as well.

**Comment by dbacchet** [comment]
@sorgelig confirming that with your build I can run with no gfx glitches both terraonion and darksoft roms too

**Comment by 8bits4ever** [comment]
> try this build:
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/8403452/NeoGeo.zip)

Confirming, this build works too

**Comment by sorgelig** [comment]
ok. released.
