### ISSUE TITLE
Question: Renaming Game Titles

### ISSUE THREAD

**Issue by Chromagram** [MiSTer-devel/NeoGeo_MiSTer#163]
Hello,

Sorry if this is an easy answer, but how do you rename how NEO•GEO games are titled in the menu? I just imported a set from online and I'd prefer to not have it title like "King of Fighters 2003, The". Is there a way to rename this to my preference?

Thank you!

**Comment by sorgelig** [comment]
Depending on rom kind you use. Some roms get names from romsets.xml file.

**Comment by HiroiSekai** [comment]
Thanks, does that mean I can either try a different ROM to see if it names it my preferred way or possibly edit the name in the romsets.xml file? Or would that break it somehow?

**Comment by sorgelig** [comment]
displayed names don't break anything

**Comment by Toryalai1** [comment]
This issue can be closed
