### ISSUE TITLE
metal slug x warning

### ISSUE THREAD

**Issue by xenyou** [MiSTer-devel/NeoGeo_MiSTer#171]
metal slug x show the warninng and does not boot.

maybe it's the same issue as #50 .
but it can't boot even if I switched to AES mode.

![Screen Shot 2022-10-07 at 6 37 13](https://user-images.githubusercontent.com/832358/194423425-e1cf6697-14f0-4c86-afb1-48b737b3e758.png)

thanks.

**Comment by sorgelig** [comment]
May be you use specific ROM. I've just tried Metal Slug X with UNIBIOS 4.0 (mode: EUROPE, ARCADE). It works fine.

**Comment by xenyou** [comment]
My rom is extracted from "NEOGEO Arcade Stick Pro".
And it seems that the files are the same as humble bundle's one. (I checked md5)

https://github.com/MiSTer-devel/NeoGeo_MiSTer/blob/master/releases/gog-broken-romsets.xml

OK. Mister does not support it. right?

FYI, this rom works fine with mame.

**Comment by sorgelig** [comment]
it seems darksoft version has patch (in prom part) against this warning.

**Comment by xenyou** [comment]
I found a hack to avoid the warning. Modifying just 2 bytes can boot.

https://neo-source.com/index.php?PHPSESSID=4g9lbj277de6afgb1hd4eo9eb5&topic=408.msg4464#msg4464

but another issue happened!!

![Screen Shot 2022-10-08 at 16 04 12](https://user-images.githubusercontent.com/832358/194695408-7267f2e5-1627-4a5b-ae74-da1f064b690c.png)

oh...

**Comment by birdybro** [comment]
Cute bird :)

My advice is to try `Darksoft Neo Geo 2020-05-12.7z` from the `HTGDB-Gamepacks` archive on archive.org

**Comment by sorgelig** [comment]
Issue doesn't happen on correct rom.
Closing.

**Comment by xenyou** [comment]
I found a information.
Okay, I understood Mister needs PATCHED ROM for avoiding security.

https://twitter.com/furrtek/status/1148698502828044288
