### ISSUE TITLE
Audio needs a boost.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/NeoGeo_MiSTer#173]
The overall audio sounds great, but I think ADPCM in general sounds lower than real hardware if we compare with PSG and FM sound sources (it's true that not all consoles have the same sound balance, but it usually affects the PSG on them). Maybe a volume balance in the core for the different audio sources would help for getting a better experience.

**Comment by birdybro** [comment]
Do you have a recording handy from original hardware to compare so the adjustment could be made relative to that?

**Comment by birdybro** [comment]
That controller behavior is normal. All cores do it. The first controller to press a button gets assigned as player 1, then the next gets assigned player 2, and so on... So that's why.

**Comment by PepAlacant** [comment]
I made testings with Darksoft rom images. I was using NEOSD set and with Darksoft set the problems I mentioned didn't appeared.
