### ISSUE TITLE
Real bout - Overflow frame presentation screen

### ISSUE THREAD

**Issue by aldreypires** [MiSTer-devel/NeoGeo_MiSTer#174]
Hello!!
I noticed a bug in the game 'real bout' in the core of neogeo. Follow the description:

- In Neo Geo Core, select the real game bout

- View the initial presentation

- Observe a piece of the presentation on the right side according to image "IMG-01"

![image](https://user-images.githubusercontent.com/120674806/207936275-f69603d0-126f-4558-a22e-c16244b034e2.png)

Follow video below:

https://user-images.githubusercontent.com/120674806/207936370-9781ee02-07d0-4b34-a675-eb8af2189289.mp4

**Comment by paulb-nl** [comment]
Fixed in release 20221224

**Comment by ZmaxAldrey** [comment]
Thanks @paulb-nl !!

I just tested it and everything is OK!!
