### ISSUE TITLE
Pop 'n Bounce: two-player game with spinner & joystick

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/NeoGeo_MiSTer#178]
In a single-player game, setting _Input: Spinner_ and also setting the software dip settings to paddle allows the game to be playable with a spinner controller. However, in a two-player game where one player is using a spinner and the other player is using a controller, only one of the players is able to move correctly. Setting _Input: Joystick or Spinner_ does not seem to resolve the issue. I'm not sure if it is possible to solve this issue (perhaps both controllers always need to be the same type).

**Comment by sorgelig** [comment]
usually it's expected both players use the same kind of input devices. They aren't exactly must be the same model, but should be the same type.
