### ISSUE TITLE
Graphical glitch in Neo Turf Masters

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/NeoGeo_MiSTer#18]
There's a small one line vertical glitch accross the HUD during gameplay (near the 50% mark across 
 the yellow arrow and the "shot power" text). This can't be seen on real hardware.

The issue can be seen on this video capture: https://www.youtube.com/watch?v=q5oaXEZiATY starting at 1:14

**Comment by emmetoneillpdx** [comment]
I noticed this also. There is a similar, linear vertical glitch on the left side of the putting power meter. Probably the same bug. It looks as if the interface is shifted over by 1 pixel at that point, rather than a row of pixels being missing.

**Comment by uncon** [comment]
Adding a picture of my actual hardware (MVS).
![Neo_Geo_MVS](https://user-images.githubusercontent.com/321419/75180144-312f7900-5701-11ea-9c2a-16b37bb75745.jpg)

And, here is the same shot from the MiSTer.
![MiSTer](https://user-images.githubusercontent.com/321419/75180154-35f42d00-5701-11ea-8a0f-b8c2336840ec.jpg)

I hope this helps.

**Comment by xmcj** [comment]
I am also experiencing this issue.

The issue persists when using both official and UNIBIOS.

**Comment by furrtek** [comment]
https://i.imgur.com/FcJ2QBY.gif

#34 #81 #83

**Comment by furrtek** [comment]
Should be fixed with 77a2a8e516ac75d3afb46d85ce70faa5dcc21a99. Please close issue if confirmed.
Thanks for reporting :)

**Comment by uncon** [comment]
I just verified that this does resolve the issue I was seeing. Thank you, @furrtek!
