### ISSUE TITLE
Document NeoGeoCD Bios files

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/NeoGeo_MiSTer#184]
Could somebody please open a PR to document which cd bios files are compatible with the core in the README.md file?

Thanks!

**Comment by sorgelig** [comment]
you need uni-bioscd.rom

**Comment by theypsilon** [comment]
top-sp1.bin also seems to be compatible according to my testing.

**Comment by sorgelig** [comment]
if you use uni-bioscd.rom then you don't need other BIOSes. Unibios handles both CD and CDZ.

**Comment by sorgelig** [comment]
documented
