### ISSUE TITLE
[NGCD] Folder Sorting

### ISSUE THREAD

**Issue by adriannabarro** [MiSTer-devel/NeoGeo_MiSTer#185]
Hey,

This may be my OCD playing up, but with MVS/AES and CD sharing the same folder, when loading a *.CHD or *.CUE file, you see all the non-CD ROM folders. 

Creating a subfolder (e.g. _CD) is shown below folders with names starting with an alpha character. e.g.

```
..
2020bb
2020bba
2020bbh
3countb
_CD
```

Is there a recommended naming convention or a romsets.xml -like file to get the CD titles to sort like the AES/MVS roms do?

**Comment by sorgelig** [comment]
underscore symbol is latest in alphabet sorting. Try some symbols on shifted keys with numbers.

**Comment by adriannabarro** [comment]
That works! Thank you
