### ISSUE TITLE
Dedicated Neo Geo CD folder

### ISSUE THREAD

**Issue by joshewah777** [MiSTer-devel/NeoGeo_MiSTer#186]
Would It be possible to add a dedicated "Neo-CD" or "NeoGeo-CD" folder as the dedicated folder to hold the CD files (bin/cue or CHD) similar to how the PC Engine/Turbografx CD cores handles CD games vs HuCards? i.e. "TGFX16" for HuCards and "TGFX16-CD" for CD-ROMs?

Right now Its a bit of a mess with CD games and AES/MVS ROMs in the same folder. I'd like to have the CD games on a separate storage  like how I have HuCards on my Mister's main SD card and CD games on a separate SSD.

**Comment by sorgelig** [comment]
Ok. I'll make it

**Comment by joshewah777** [comment]
Thanks, Sorg!
