### ISSUE TITLE
Sound issue in Viewpoint

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/NeoGeo_MiSTer#19]
There's a sound issue in Viewpoint with the charging shot sfx : the sound should be looping as long as the charge is hold but actually it's cut and restarted after a delay (contrary to the behavior on real hardware). 

The problem can be spotted in the following video during the attract mode : (https://www.youtube.com/watch?v=xVhZ3Lv3iIY starting at 0:42)

**Comment by sreuter** [comment]
I see similar issues with my homebrew game, which doesn't happen on my MVS.

I use Blastars NGFX Soundbuilder and the ADPCM-B BGM (while actually set to looped), is stopping after the first play. The driver is also playing sounds via a round-robin approach on the available ADPCM-A channels, but sometimes there are not playing.

Apart from those sound issues, I'm super happy with the core and will soon use the MiSTer it as a replacement for MAME in my dev loop :)

**Comment by sorgelig** [comment]
@sreuter since you are developer, may be you can identify more precise what YM2610 register setting or something else causes it (from NeoGeo development side).

**Comment by jotego** [comment]
Are you using the repeat bit (bit 4) in your software? That’d be a good
hint.

**Comment by jotego** [comment]
Maybe you could try commenting changing file jt10_adpcmb_cnt.v like this:
// around line 97
            else begin
                if(arepeat) begin
                    addr <= {astart,8'd0};
                    nibble_sel <= 'b0;
                end else set_flag <= 'd1;
            end

I assumed that a flag should be raised at the end of a count but maybe it should only be raised if the repeat bit is 0.

Sorry I don't try it myself, I don't have the setup ready.

**Comment by MP2E** [comment]
I tried Viewpoint with a build made with the changes @jotego described, but the sound effect for charging still seems to be cut and restarted with a delay

**Comment by loloC2C** [comment]
Rysha explained on discord how to get into the hidden menu in order to toggle on/off specific sound chips so I could give more information about the current issue:
It sounds like both some part of the music (break beat + voice fx for the first level) and sound effects (the shots, shot charging and explosions) are mixed together on ADPCMA and it's where the problem I described occurs.

**Comment by loloC2C** [comment]
another easy to reproduce sound issue for this game (still on ADPCMA part):
start a game and do nothing so you can die quickly, when the continue ? message appears there should be a sfx played each time the counter decreases but on the current version of the core the sfx is only played 1 out of 2 times.

**Comment by loloC2C** [comment]
Fixed in Release 20191113
