### ISSUE TITLE
Sound issues when loading battles on Shinsetsu Samurai Spirits Bushidō Retsuden

### ISSUE THREAD

**Issue by leonquest** [MiSTer-devel/NeoGeo_MiSTer#190]
Context:
https://twitter.com/PricePartDeux/status/1679667221243785216?s=20

**Comment by Zet-sensei** [comment]
Seems to be fixed with PR https://github.com/MiSTer-devel/NeoGeo_MiSTer/pull/193.

**Comment by sorgelig** [comment]
OK. Closed.
