### ISSUE TITLE
[NeoCD] Stakes Winner - Not enough space available for Backup RAM message

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/NeoGeo_MiSTer#191]
KremlingKuthroat19 informs us on Discord about an error message when trying to play Stakes Winner on the 20230718 unstable core revision.

After the initial loading sequence, we have an on-screen with a character explaining the game doesn't have enough memory for Backup RAM.

The same message appears with a fresh Memory Card and even with AutoSave ON and OFF on the core.

I can confirm that error message on the original CD & CDZ bioses + UniBIOS on my side.

The game cannot go further and reboot to the BIOS CD player after that.

**Comment by Zet-sensei** [comment]
Update from the user - If you clear 100% of the save data on the Data Manager, the game works.

**Comment by KremlingKuthroat19** [comment]
Sorg just added individual saving per CD w/ the latest unstable build. I tested this out and the issue is solved. Would you mind closing the ticket @Zet-sensei when you get a chance?

**Comment by Zet-sensei** [comment]
As per requested & tested also on my side too, ticket closed as resolved.

Thanks for the feature request.
