### ISSUE TITLE
Feature Request: Have save memory allocated per game, not whole system

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/NeoGeo_MiSTer#192]
On the MiSTer Discord, I ran into an issue with Stakes Winner that was just documented. The game only works if 100% of your internal save memory is erased as evidenced here: https://github.com/MiSTer-devel/NeoGeo_MiSTer/issues/191

To my knowledge, the Sega CD and upcoming Saturn core have a feature where the internal data of the system is created as a brand new instance for every game file and saves it's own clean system data per game using the game's name as a save file. The PSX core does the same thing except with memory cards versus internal memory.

Can we have this feature for Neo Geo CD games?

**Comment by sorgelig** [comment]
I've pushed commit into Main repository to make save per CD.
You can try it in unstable builds.

**Comment by KremlingKuthroat19** [comment]
This works now! The real problem is that Stakes Winner needs to have a completely free system data to save. What a hog! Thanks so much for fixing this in record time. Closing the issue now :)
