### ISSUE TITLE
Folder behavior for CD images does not match other cores (selecting folder does not load disk image)

### ISSUE THREAD

**Issue by Dinierto** [MiSTer-devel/NeoGeo_MiSTer#194]
Currently in cores such as Sega CD, TGCD, and PSX, when CD images are in folders and the folder is selected, the game is automatically loaded without having to open the folder first (unless there are multiple discs I believe).  In Neo Geo, as it stands, this behavior is not reflected; one must open the folder first.  Changing it would make it more consistent with behavior of other cores, and of course have the mild benefit of saving "clicks"

**Comment by SuperRetroCity** [comment]
can confirm. multiple discs require disc selection.

**Comment by mario-64** [comment]
Confirmed and agree the behavior should be consistent with other CD cores.

**Comment by sorgelig** [comment]
fixed in new commit (Main)
