### ISSUE TITLE
KOF 94 flickering glitches strikes back.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/NeoGeo_MiSTer#195]
The issue is back and it affects only the MVS/AES version, not the CD Version. I think Gyurco did a rework of the core clocks for MiST conversion, I don't know if it could be helpful for definetively fix the MiSTer Core in this aspect..

Thanks !

**Comment by sorgelig** [comment]
should be fixed fixed already

**Comment by PepAlacant** [comment]
FIXED
