### ISSUE TITLE
[NEOCD] Flickering pixels on-screen after recent commit (fix async clocks and latches).

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/NeoGeo_MiSTer#196]
After commit https://github.com/MiSTer-devel/NeoGeo_MiSTer/commit/90a8350c4e7fafb64067cf777b58a93bc7511fdc, the Neo Geo CD part of the core is having flickering pixels on-screen.

The regression is visible with on the boot sequence, the CD player and in-game.

An example here, visible on the right part of the logo & the Neo Geo CD font.
![20230723_220800-screen](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/52127625/fcb705ae-e1ce-422f-9deb-124858dce633)

_EDIT : Typo._
A second user reports the same problem on Discord.
The core was compiled from the source code on Quartus Lite 17.1 for me & the other user have used the AutoBuild one on Discord (unstable nightlies).

**Comment by PepAlacant** [comment]
Yes, with that build the flickering problems are present. KOF 94 in AES-MVS has the same issue too.

**Comment by sorgelig** [comment]
it's known issue

**Comment by Zet-sensei** [comment]
Fixed with PR https://github.com/MiSTer-devel/NeoGeo_MiSTer/pull/197.
