### ISSUE TITLE
Last unstable zoom glitching.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/NeoGeo_MiSTer#198]
There is zoomglitching and vertical line problem in the last unstable build with new clocks. It's very noticeable in the NEOGEO jingle logo. The artifacts appear when letters zooming. 

It affects MVS/AES and CD modes.

Kof 94 problem still persists (only AES/MVS)

**Comment by sorgelig** [comment]
try build with new changes

**Comment by wwark** [comment]
Someone on discord said it is fixed. It could be closed.
