### ISSUE TITLE
Metal Slug 1 issue with last changes on clocks

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NeoGeo_MiSTer#199]
Hi,

Testing this commit https://github.com/MiSTer-devel/NeoGeo_MiSTer/commit/6cefe537c735c1b78ab339d24118e62f4567abd0

In the first part of the stage of Metal Slug 1 we can spot the of lot of black pixels shown on the picture below
![20230726_064902-screen](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/469461/c758fdfe-4ba7-4a9e-8f23-906b03afa482)

Thanks

**Comment by sorgelig** [comment]
i've pushed the commit fixing it.
