### ISSUE TITLE
Loading screen on boot

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/NeoGeo_MiSTer#20]
Hi

I dont have any neogeo and i dont know how they boot with a cartridge/disc but isn't possible to load bios or have a by default game loaded? so we don't have that black screen?

**Comment by sorgelig** [comment]
Original console expects cartridge inserted before power.
Loading process of NeoGeo ROMs is complex. May be in the future it will be possible to set some ROM to load on startup.
It's supposed to open OSD menu in released version. Don't you see OSD?

**Comment by eubrunosilva** [comment]
Hi.
yes i see the open osd :) i tought I've pressed f12 because I was used to do this :)
thanks
