### ISSUE TITLE
Art of fighting 3 vertical line clipping 

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/NeoGeo_MiSTer#202]
There is a bug when zooming in and out in art of fighting 3. It is visible in every stage in the game. 
![image](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/82502378/49ec11d0-faad-4308-845e-cd92de0da0c7)

To recreate, select a random character (Ryo for example), and just jump around. You will be able to see it

**Comment by Toryalai1** [comment]
This needs confirmation

**Comment by Toryalai1** [comment]
This is a confirmed core issue.

**Comment by paulb-nl** [comment]
Confirmed original hardware issue. It is difficult to see because of the compression but check this video from AES:
https://youtu.be/d8i9O6dHREg

**Comment by Toryalai1** [comment]
Atrac17 will produce some videos which will be shared here. He did mention that the issue occurs on the core and MAME, but not original hardware

**Comment by sorgelig** [comment]
on video from paulb-nl post i clearly see artifacts on right side. And it seems from original HW. 
Some TVs and capture devices may cut the sides and make it invisible.

**Comment by PepAlacant** [comment]
The artifacts in the overscan zone won't be visible never on a CRT TV.  They are normal and should be produced by real hardware.

There are worst cases that are completely normal, like KOF 96 ( MVS cart version )

The Horizontal artifacts in the PAL horizontal overscan are normal too ( magician lord, burning fight, etc )

I don't think this is an issue at all.

**Comment by PepAlacant** [comment]
I just confirmed this with OSSC. The line clipping on the overscan is normal.

**Comment by Toryalai1** [comment]
@PepAlacant uses AES console, the issue is on the MVS version. I’m still waiting for footage and I will paste it here.

Thank you very much for your and Paulb-nls work on the fixes.

**Comment by Toryalai1** [comment]
https://www.youtube.com/watch?v=JyaaCufyLnY

I found a recording from real MVS hardware. The clipping doesn't happen during zooming @paulb-nl

**Comment by paulb-nl** [comment]
@Toryalai1 That video is cropped on the sides so it is hidden. Compare the space on the left and right of the life bars from the video that I linked to.
