### ISSUE TITLE
Minor Fighter's History Dynamite CD problem.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/NeoGeo_MiSTer#204]
NEO GEO CD : 
There is an error in FIX layer "Now Loading Screen" of Attract Mode when Demo Mode is selected. It doesn't affect the loading screens of main game. Very minor problem, doesn't affect the game in other ways.
![IMG_4230](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/75079781/0d102a8d-ea2a-49f4-8267-0d1d4450ed06)

**Comment by paulb-nl** [comment]
Thanks. This issue confirmed that the Timer IRQ can be masked with register $FF0004.

Otherwise the Timer IRQ will write to VRAM while the System rom is writing to the FIX layer in VRAM.

**Comment by PepAlacant** [comment]
Tested and Fixed !
