### ISSUE TITLE
Metal Slug clicking sounds

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/NeoGeo_MiSTer#207]
I’m not sure whether or not a real NeoGeo does this, but in Metal Slug 1, at the very first stage boss, if you let it fire a huge laser, the charging sound has weird clicks in it. It happens every time the boss charges the laser, but can easily be missed if you defeat the boss too quickly.

**Comment by Toryalai1** [comment]
What core version?

**Comment by MP2E** [comment]
Latest unstable version, though I think this bug has been around for a while. I remember encountering it back in 2020 or so

**Comment by MP2E** [comment]
Thanks PepAlacant, I see you are quite familiar with the NeoGeo. I will close the issue!
