### ISSUE TITLE
Metal Slug 2 Graphic Artifacts

### ISSUE THREAD

**Issue by knightofl** [MiSTer-devel/NeoGeo_MiSTer#212]
https://youtu.be/m1JOfFGxbdU
Metal Slug 2, NeoGeo_20230803.rbf.

**Comment by Toryalai1** [comment]
This happens on real hardware as well. See the following video: https://www.youtube.com/watch?v=F3eC8O47EvI&t=97s

**Comment by sorgelig** [comment]
Thanks to @Toryalai1 to find the right video.
Confirmed as not a core issue.
