### ISSUE TITLE
King of Fighters 2001 bug

### ISSUE THREAD

**Issue by black-francis** [MiSTer-devel/NeoGeo_MiSTer#214]
AES mode with unibios has glitched sprites on the controller config screen. Game locked up once when trying to enter a button mapping on that page too.

AES mode with original bios main select screen looks off, no background sprites or proper fonts for the lettering. Clicking on option shows no text at all, but you can still hear and control the game. 

Using a .neo ROM set.

UNIBIOS
![UNIBIOS](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/44230562/138bf7ba-5181-45b6-b763-3664cdf0f3d4)

ORIGINAL
![ORIGINAL BIOS](https://github.com/MiSTer-devel/NeoGeo_MiSTer/assets/44230562/1f6eac08-dd4f-42a6-9868-8d8585844ecf)

**Comment by Toryalai1** [comment]
Same result and behaviour with darksoft set

**Comment by paulb-nl** [comment]
This game has a different rom set for MVS and AES so you should use the correct one.  kof2001h is for AES.

The AES version does not have button config in options.

Most likely the same thing will happen on a real Neo Geo.

**Comment by Toryalai1** [comment]
It is confirmed now that this also happens on real hardware. Issue can be closed

**Comment by black-francis** [comment]
Sorry for the false alarm, stupidly hadn't considered the issue was not using an AES ROM, game functions perfectly with them. Thanks everyone.
