### ISSUE TITLE
Metal Slug 3

### ISSUE THREAD

**Issue by MrsBison** [MiSTer-devel/NeoGeo_MiSTer#216]
At Stage 3 i discovered a small grafik glitch.

You need to take the Ostrich slug path.....
While scuba gearing ... dont enter the bottom entrance .... 
Keep on swimming and destroy the upper right rocket shooting base. 
There are two of it. Than you reach another place where you can ride the Ostrich Slug... 
On this levelsection youll notice on the top of the screen some small flickering horizontal lines. 

Used Core = 20231204

https://www.youtube.com/watch?v=8EbJDIVo-xY

This is the only MGS glitch i discovered so far and i playe all parts alot.
Hope this can be fixed. :)

**Comment by paulb-nl** [comment]
This game has a lot of glitches on original hardware so this is how it should be.

See this video: https://youtu.be/E-mfy_ZljSo

**Comment by MrsBison** [comment]
Too bad that the playing guy didnt choose the Ostrich Slug route but while the shooting base is collapsing you can 
also see on the top these flickering small lines.

Original Hardware or not... maybe **sorgelig** will have a look on it...

It wouldn't be the first game that would be better as an emulation than on original hardware.

Just some thoughs about a wonderfull francise :) 

Thanx for reply

**Comment by Missingno255** [comment]
> Too bad that the playing guy didnt choose the Ostrich Slug route but while the shooting base is collapsing you can also see on the top these flickering small lines.
> 
> Original Hardware or not... maybe @**sorgelig** will have a look on it...
> 
> It wouldn't be the first game that would be better as an emulation than on original hardware.
> 
> Just some thoughs about a wonderfull francise :)
> 
> Thanx for reply

These cores are meant to be as accurate as possible to the original hardware, not be another awful inaccurate software emulator. @sorgelig doesn't need to do anything. If you want inaccurate emulation, look to MAME or Kawaks, you won't find any problems there ;)

**Comment by sorgelig** [comment]
I don't have real NeoGeo HW, but such issues often happen on real HW too. In HDMI you usually see a little more than it was on CRT.

**Comment by MrsBison** [comment]
@sorgelig 

Thanx so much for your kind reply. 
I never said that it has to be change or something like that. It was just a question depending on this great work and maybe the option to fixe something and make it from outstanding to perfect. The point HDMI Vs. CRT is a very good point. Too bad i never thought that way. I do own lots of retrosconsoles including a Neo Geo AES but i dont have MGS 3. MGS Modules are very expensive this day.

So we can close this topc now
