### ISSUE TITLE
Black irregular flickering?!

### ISSUE THREAD

**Issue by TsukiZero** [MiSTer-devel/NeoGeo_MiSTer#217]
Observed this when watching someone stream Aero Fighters 3. IDK what may be the cause, thought of informing:
https://clips.twitch.tv/ElatedResourcefulChinchillaTBTacoRight-d8hQEprTgcHN-rf4

**Comment by paulb-nl** [comment]
That is just a problem with his capture card. It does not the like the refresh rate of the Neo Geo.

**Comment by TsukiZero** [comment]
> That is just a problem with his capture card. It does not the like the refresh rate of the Neo Geo.
Ah, thanks for explaining so. I was starting to get worried, because everything was fine until the Neo Geo.
