### ISSUE TITLE
MVS core sound speed slower than real MVS board

### ISSUE THREAD

**Issue by okami2012** [MiSTer-devel/NeoGeo_MiSTer#224]
i hear kof98 sound speed slower than real mvs board

**Comment by Toryalai1** [comment]
Can you provide recording that is from real hardware vs mister?

**Comment by okami2012** [comment]
OK wait me for some days，I'll record it

**Comment by okami2012** [comment]
> Can you provide recording that is from real hardware vs mister?

OK wait me for some days，I'll record it

**Comment by okami2012** [comment]
> Can you provide recording that is from real hardware vs mister?

I can't find my MVS substrate power supply. Can I use MAME's sound as a substitute reference

**Comment by okami2012** [comment]
> Can you provide recording that is from real hardware vs mister?

https://www.youtube.com/watch?v=7RvxTrD7M80 this is mvs version
https://www.youtube.com/watch?v=YlYWXF7D2xM&t=75s this is mister version

**Comment by Toryalai1** [comment]
That MiSTer recording seems to be from 3 years ago. The neogeo core has, as of recent been rewritten. I tried with the latest core version and I cannot hear a difference in speed

**Comment by Toryalai1** [comment]
It seems like VGM side is using MAME for recording. Can you do the same comparison but use real hardware vs mister?

**Comment by okami2012** [comment]
> It seems like VGM side is using MAME for recording? Can you do the same comparison but use real hardware vs mister?

wait.....let me find my mvs power

**Comment by Toryalai1** [comment]
Make sure the core is running in vsync_adjust=2 and that it is running in MVS mode

**Comment by okami2012** [comment]
> It seems like VGM side is using MAME for recording? Can you do the same comparison but use real hardware vs mister?

sorry I try to power on my MVS board but no signal also from my ossc or GBSC，I think it's need repair TAT

**Comment by okami2012** [comment]
> It seems like VGM side is using MAME for recording? Can you do the same comparison but use real hardware vs mister?

I found a video from Youtube I will make a new video for you Thank you very much

**Comment by okami2012** [comment]
> It seems like VGM side is using MAME for recording? Can you do the same comparison but use real hardware vs mister?

Sorry, I tried comparing it with the real board and there was no difference between it and the Mister. It should be a problem with MAME, but I didn't expect that after so many years, MAME is still not as accurate as the real board! I'm very sorry for taking up your time!

**Comment by Toryalai1** [comment]
It is ok. Please close ticket
