### ISSUE TITLE
Choosing a BIOS

### ISSUE THREAD

**Issue by TorgoPSN** [MiSTer-devel/NeoGeo_MiSTer#23]
I'm not seeing a way to "choose a BIOS" as described in the README, so it seems to always initiate 000-lo.lo, which only nets me the debug for the NG Hardware (no Dips are on though), to do Memory and input tests etc. Not sure what I'm doing wrong, but I've followed everything described in the README so far. Most of my ROM sets in the folders are working with the XML file, so I'm only trying those currently.

I'd like to just use the UniBIOS since that's what I have in my AES, but I included all of the BIOS files that were listed.

Thank you for getting this released, I love my Neo Geo AES and the platform, but having it with everything else on the MiSTer is too cool to not setup.

**Comment by sorgelig** [comment]
Please use Forum for discussion. 
Github is for issue reporting or development collaboration.
