### ISSUE TITLE
Neo Drift Out - sound effects cutting out

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/NeoGeo_MiSTer#25]
The engine and even the announcer/co-pilot will have their sound effects/voice samples cut out and go silent when they shouldn't.
This seems to happen on long straight roads in the game, you can hear the engine sound cut out, and sometimes the announcer/co-pilot as well.

32MB SDram, neo geo core 20190908

Examples:
1: https://youtu.be/5prSJgpMHbc?t=14
2: https://youtu.be/5prSJgpMHbc?t=24
3: https://youtu.be/5prSJgpMHbc?t=56
4: (co-pilot cuts out in this one also): https://youtu.be/5prSJgpMHbc?t=122

**Comment by jotego** [comment]
First of all, I didn't know that game. It looks really cool!

The bug:
@sorgelig probably thinks we are missing data writes. It could be. I took a lot of care about this but if data is written faster than the pipeline it may get lost. As the sound core developer, I tend to blame the system for these things. Could there be something speeding up the Z80 interaction?
Looking at the core itself, it may be another case of misinterpretation of the YM2610 specs. Or just a typo.

**Comment by sorgelig** [comment]
I don't have strong opinion here. Z80 is working on its original speed as on real HW as far as i know.

**Comment by M-Walrus** [comment]
I have notes several other areas where sound is cutting out incorrectly. sometimes this is in music tracks and sometimes with sound effects, it seems. perhaps they are using the same sound channel in both.

Other examples:
- Waku Waku 7 intro music: Drums are only playing first part of the loop, 2nd part is completely missing
- Breakers / Breakers Revenge: Music when in character select screen cuts out after about 6 seconds, sounds like it should be looping.

Would you like these to be put in to separate incidents on the issue tracker, or just leave reference to them here?

**Comment by jotego** [comment]
It’s great to have more examples in this thread. Thank you.

**Comment by M-Walrus** [comment]
Another example of missing music:
Nightmare In The Dark is missing parts of pretty much every music track I heard. It should be continuous through most of the game, but half of it is silent.

**Comment by Dubon77** [comment]
I tested neo drift out and cant reproduce this anymore on the latest build. Can be closed afaik

**Comment by M-Walrus** [comment]
This issue was resolved by one of the recent fixes GreyRogue made.

Closing.
