### ISSUE TITLE
All audio drops out

### ISSUE THREAD

**Issue by blackjer** [MiSTer-devel/NeoGeo_MiSTer#29]
After the update on 9/11/19 the neo geo core loses all audio. Once, i was able to restore audio by deleting the config files in /media/fat/config but this latest time, that is not correcting the issue.

**Comment by jotego** [comment]
Aré you saying that you do not get any audio output at all for any game?

**Comment by Breiztiger** [comment]
first launch of game i have sound but after select another game no sound
i must reload core

**Comment by blackjer** [comment]
build on 9/13 has corrected the issue.  Thank you!
