### ISSUE TITLE
Black levels incorrect after recent update

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/NeoGeo_MiSTer#30]
Black is now showing as dark grey in the Neo-Geo core, you can tell when you first boot it up, the contrast in color between the video output area and the borders over HDMI. 

Previously the Neo Geo logo would show with a black background that matches the unused border space of 16x9 display. Now is displays with a grey background that contrasts against the black border space.

Change happened in an update between 9-11 and 9-13. Just noticed today, and all my older videos using the 20190908 build and prior are correct.

Previously it looked like this (the way it should look): 
![neo geo proper](https://user-images.githubusercontent.com/40709481/64837048-3f099b80-d5b2-11e9-9714-88b0c33ca251.png)

Now, it looks like this (incorrect, notice the grey box now):
![neo geo updated blacks wrong](https://user-images.githubusercontent.com/40709481/64837063-45981300-d5b2-11e9-82c4-9b1bf2d293c0.png)

Proof it should look like the first example from an actual MVS hardware recording: 
https://youtu.be/8ymGVLbg1c4?t=8

**Comment by paulb-nl** [comment]
This is corrected with #32. Now both black and white levels are correct.

**Comment by M-Walrus** [comment]
Confirmed fixed. Closing issue.
