### ISSUE TITLE
SSG does not sound right

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/NeoGeo_MiSTer#31]
It sounds like the SSG is not right, here is a reference from Metal Slug during the prisoners count and bonus count at the end of a stage:

capture from MVS real hardware: https://youtu.be/8ymGVLbg1c4?t=115
capture from MiSTer core: https://youtu.be/bZ0wQHPC0G0?t=296

**Comment by jotego** [comment]
Try changing line 444 of jt12_top.v that looks like:

            .sel        ( 1'b1      ),  // half clock speed
to
            .sel        ( 1'b0      ),  // half clock speed

It may well be that YM2610 has that set to 0 while YM2203 has it set to 1. Let me know how it goes.

**Comment by loloC2C** [comment]
I've tried to change the line in your comment with the half clock speed however it only changes the pitch (which sounds more right imo) but there are still cracks in the sfx using the ssg

**Comment by MP2E** [comment]
Yes I think the half clock speed change is correct, pitch seems accurate now

**Comment by jotego** [comment]
I have the real part but cannot measured it without a socket adapter. I have ordered one. Once I receive it I will measure it and compare with my FPGA implementation. Just bear with me.

**Comment by jotego** [comment]
@sorgelig please update to latest jt49. I have fixed a typo that @loloC2C found.

**Comment by sorgelig** [comment]
If you mean half clock, then it's already fixed in NeoGeo core.

**Comment by sorgelig** [comment]
oh, i see.. wrong index

**Comment by jotego** [comment]
I have submitted a pull request that I think fixes this. See the attached RBF file to quickly check it.

[NeoGeo_20191005.rbf.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/3693081/NeoGeo_20191005.rbf.zip)

**Comment by loloC2C** [comment]
I tested the build, while the pitch sounds right the cracks are still there.

**Comment by jotego** [comment]
The Metal Slug prisoner count seems fine to me now. The Nasca logo also seems fine.
Maybe the cracks are a different issue. We'll need more an example to examine. With just "cracks" I cannot imagine the problem.
Can you confirm that the two reported examples are fine to you too? Metal slug and Nasca logo?

**Comment by sorgelig** [comment]
funny, i didn't close it explicitly.. PR acceptance closed it automatically.

**Comment by jotego** [comment]
Good automation script. 
There is at least one more bug out there. I’ll go hunting later.

**Comment by jotego** [comment]
I include the RBF here again. The alarm sound while **continue** is shown in Metal Slug sounds correctly now, at least compared with MAME. There was still an ugly bug related to the envelope generator reset. Another bug that would cause silent when it shouldn't be silent and then another minor bug.
I think after this we should be able to close the issue. Please @loloC2C check the different sounds and come up with new examples if you find something else.
[NeoGeo_20191005.rbf.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/3693585/NeoGeo_20191005.rbf.zip)

**Comment by loloC2C** [comment]
It's way better ! Night and day compared to the previous build. I think there's still a little of the issue but I'd need to compare with real hardware. Thanks and congrats !
