### ISSUE TITLE
Art of Fighting: Character portrait over the edge of white border

### ISSUE THREAD

**Issue by NEO-JAMMA** [MiSTer-devel/NeoGeo_MiSTer#34]
This is comparing MiSTer (NeoGeo_20190915.rbf) with my AES (no Unbios).

MiSTer: The characters portrait is going over the edge on the right of the white border around it.
![IMG_20190915_175627514 1](https://user-images.githubusercontent.com/13951468/64960014-65546300-d860-11e9-872d-fd637446ef36.jpg)

AES: The characters portrait is inside the  white border
![IMG_20190915_155220806 1](https://user-images.githubusercontent.com/13951468/64959954-49e95800-d860-11e9-8561-4e1773615324.jpg)

**Comment by furrtek** [comment]
Should be fixed with 77a2a8e516ac75d3afb46d85ce70faa5dcc21a99. Please close issue if confirmed.
Thanks for reporting :)

**Comment by sorgelig** [comment]
i've checked. 
it's fixed.
