### ISSUE TITLE
processing rom files

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/NeoGeo_MiSTer#35]
Hi
I know that we already have darksoft roms that are already patched and decrypted so no need to do more work here
but some people doesn't have this pack and have mame (also hbmame) could be easy to find and copy the zips to the card.
do you think its possible, in the future, have an on the-the-fly decrypt and patch (for some games - at least metal slug x has this problem)?
Thanks

**Comment by sorgelig** [comment]
I've added .neo files support.
Use Terraonion utility to convert mame roms into .neo  
For most games it will work. Still some games require hacks to remove protections, so few games won't work in neo format.

**Comment by eubrunosilva** [comment]
neobuilder only works with oficial mame romsets :(

**Comment by sorgelig** [comment]
You can make converter for unofficial roms if you wish. Actually all unofficial (not included in mame) ROMs are based on mame set. So you can re-use neo files as part of decrypted set for any mod.
Almost every NeoGeo rom has unique things for protection. And there are many such roms. Working with unknown rom set will require additional info anyway to tell which game is it, so specific decryption will be used.

All in all, if you don't like easy path (darksoft) then you can invent more harder path with custom decryptors and other utilities. Up to you.
