### ISSUE TITLE
Narration dropout in intro to Garou: Mark of the Wolves

### ISSUE THREAD

**Issue by bfbiii** [MiSTer-devel/NeoGeo_MiSTer#40]
Two lines are dropped in the intro:
1) "But here, they do not exist."
2) "For here, THE MIGHTY RULE!"

Original
https://www.dropbox.com/s/kl2l27lr71u3ywc/Original-NoDrops.wav?dl=0
MiSTer
https://www.dropbox.com/s/aefbo7a8hqh5xgy/MiSTer-DroppedLines.wav?dl=0

**Comment by the-importer** [comment]
There seems to be SFX and Voice drops in many games. In KoF2000, the cursor section noise drops 
1 out of 3 times. I tried with both HDMI sound and Analog output from the IO board, same thing. I also tried with both the Stereo mix option at 50% and None, no difference.

I'm using NeoGeo_20191014 BTW.

**Comment by Dubon77** [comment]
The missing audio in garou is fixed, i think this can be closed
