### ISSUE TITLE
IRONCLAD: Audio peaking when picking up power-ups

### ISSUE THREAD

**Issue by bitfan2011** [MiSTer-devel/NeoGeo_MiSTer#42]
Seems like when you pick up power-ups shortly after dying, the audio gets overloaded and crackles. Sometimes picking up the power-ups crackles no matter what. Sound effect for the pick-up also seems too loud.

**Comment by Toryalai1** [comment]
I cannot notice any audio pitch. Do you have a recording and do you have a recording from real hardware?

**Comment by Toryalai1** [comment]
@bitfan2011 Any updates to this?

**Comment by sorgelig** [comment]
I think bitfan2011 is not here and no other confirmed the issue. Closing.
