### ISSUE TITLE
Update JT12/JT49

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/NeoGeo_MiSTer#43]
# JT49
- EG period was 32 times shorter (!)
- Added compression to simulate different resistor loads
- Different clock divider when embedded

# JT12
- Clock divider settings do not require a r/w operation on upper address anymore
- Updated to work with latest JT49, set dynamic range to 21dB (used to be 40dB)

Some PSG instruments may sound louder now as sound is more compressed.

**Comment by jotego** [comment]
Please, someone copy the files to this repo. Please try it on NeoGeo. I have only tried these changes in Capcom cores.

**Comment by sorgelig** [comment]
are jt49/jt12 include all recent changes from NeoGeo?

**Comment by jotego** [comment]
I think so, yes.

**Comment by sorgelig** [comment]
Since i'm not working on sound, i'm not sure which version of jt10_acc is more correct. I know Grey and Kitrinx did some tweaks in mixing there.

**Comment by sorgelig** [comment]
hmm. it seems a lot of differences in adpcm.
So, i won't merge myself. May be Gray will check what to merge from original jt12.

**Comment by jotego** [comment]
I don’t know myself. I have merged in the master repo what they have asked
for but the MiSTer repo is more experimental. Let us have them check this.

**Comment by sorgelig** [comment]
should be done now.
