### ISSUE TITLE
Metal slug 2 & 3, ROM Cart warning when running under Arcade(MVS) 

### ISSUE THREAD

**Issue by Sinaloagold** [MiSTer-devel/NeoGeo_MiSTer#50]
Metal slug 2 & 3, ROM Cart warning when running under system type :Arcade(MVS). Games actually run under Console mode only. Thanks

http://imgur.com/gallery/hL6RUDL

**Comment by klaritan** [comment]
I can confirm this. I've reset a few times for it to stop, but it keeps coming back.

**Comment by sorgelig** [comment]
It's well known issue. Use AES mode.

**Comment by klaritan** [comment]
> It's well known issue. Use AES mode.

Using AES mode on OSD doesn't allow dip switch settings to save so it's not a perfect workaround sadly.

**Comment by sorgelig** [comment]
You can set AES mode in OSD and use UniBIOS where you set MVS mode.
Then these games will work.

**Comment by klaritan** [comment]
> You can set AES mode in OSD and use UniBIOS where you set MVS mode.
> Then these games will work.

Yeah, like I mentioned the games do work with this method. This is how I play them, but if you do this it won't save dip switch settings (e.g. life settings, difficulty changes and turning blood on). I know that's our best workaround for now, but I wanted to make this clear.

**Comment by eniva** [comment]
Hello, there is a better way to do this while we wait for the fix:

https://github.com/eniva/MisSTer_Guides/wiki/NeoGeo-Red-Warning-Fix

**Comment by eniva** [comment]
> 
> 
> > You can set AES mode in OSD and use UniBIOS where you set MVS mode.
> > Then these games will work.
> 
> Yeah, like I mentioned the games do work with this method. This is how I play them, but if you do this it won't save dip switch settings (e.g. life settings, difficulty changes and turning blood on). I know that's our best workaround for now, but I wanted to make this clear.

Softdips do not save under an AES hardware running UniBIOS to set it to MVS. This is a normal behavior even for the real hardware.

The issue is still a problem, but that softdips behavior is actually perfectly emulated.

**Comment by sorgelig** [comment]
I will check this workaround through patching. Probably it can be added from the core through option till full fix will be available. Unfortunately furrtek is not around long time already and it's hard to fix the core when you don't know every bit of original HW. 
So i will try to add easier workaround based on existing knowledge base.

**Comment by eniva** [comment]
> 
> 
> I will check this workaround through patching. Probably it can be added from the core through option till full fix will be available. Unfortunately furrtek is not around long time already and it's hard to fix the core when you don't know every bit of original HW.
> So i will try to add easier workaround based on existing knowledge base.

Thank you! This workaround is actually not perfect. The red warning screen actually comes up in Pulstar for unknown reason. There may be more.

**Comment by sorgelig** [comment]
it would be good to find out the actual reason why these warnings appear. What these games are checking? If i would know it, then may be i would fix it in the core.

**Comment by eniva** [comment]
I believe this has something to do with battery. Basically the memory patch unlocks the battery memory and writes it in.

I also want to share that I updated the guide because I found a way to get Pulstar to work as well.

**Comment by furrtek** [comment]
Hi, I'm currently looking at what the check does exactly. I knew about those that compare the system type with the BIOS type, but I never dug into those which use the battery-backed RAM.
Not sure if it's an access problem caused by the core or if it's because of how the battery-backed RAM file is handled.

**Comment by klaritan** [comment]
> 
> 
> Hello, there is a better way to do this while we wait for the fix:
> 
> https://github.com/eniva/MisSTer_Guides/wiki/NeoGeo-Red-Warning-Fix

Thank you for this. It works great.

**Comment by eniva** [comment]
It looks like this is fixed now. Tested with a few games and it seems to be working fine. I think it can be closed.

**Comment by klaritan** [comment]
Can confirm fixed.

**Comment by Sinaloagold** [comment]
it's fixed. Thanks everyone. 😊
