### ISSUE TITLE
The latest update (20191113) randomly drops sound effects

### ISSUE THREAD

**Issue by klaritan** [MiSTer-devel/NeoGeo_MiSTer#51]
Sound effects just stop playing at random occasions until MiSTer has to be completely restarted.

**Comment by Dubon77** [comment]
Can you clarify what games this happens in  and what your setup is?

**Comment by klaritan** [comment]
> 
> 
> Can you clarify what games this happens in and what your setup is?

My MiSTer is connected to a display via HDMI. Audio is connected to a DAC from the io board via TOSLINK slot.

I was testing Twinkle Star Sprites as the game was known to have some audio problems. It was fine for the most part, but sound effects just stopped playing. I changed to Metal Slug 3 and it was also missing sound effects, then KOF98 as well.

**Comment by sorgelig** [comment]
I'm sure it's related to DDR3 bridge lockup. It may happen sometimes. Reset button fixes the ussue.

**Comment by klaritan** [comment]
Why does this happen now?
I never had sound effect dropping in Neogeo before the update.

**Comment by sorgelig** [comment]
DDR3 lockup is present from the day 1 on MiSTer.
Use normally as before without rushing to switch the cores, and chance of lockup is minimal.

**Comment by klaritan** [comment]
I updated Neogeo, uploaded a few more roms via FTP, turned the MiSTer off completely from its power. Then I came back after an hour to turn on MiSTer, ran Neogeo core and chose to play Twinkle Star Sprites.

I've switched cores before and I never had this audio issue before this update and I've been using Neogeo for a month now on regular basis.

**Comment by Dubon77** [comment]
Theres one other person whos experienced this, who is using 32MB ram, witch ram module are you using?

**Comment by Shogun7797** [comment]
Had this issue twice yesterday.  Played puzzle bobble 2 and around level 5 sound effects cut off but music kept playing

**Comment by houseoftheed** [comment]
I'm seeing this issue on pretty much every game I try. Resetting fixes it but it comes back after either playing the game for a few minutes or leaving games running in attract mode.

**Comment by 13r** [comment]
Same problem here. I happens in many games... for example Burning Fight and Fatal Fury - King of fighter to name last ones i tried.

**Comment by sorgelig** [comment]
Would be good if others from this thread would report if problem is fixed in new release or not.

**Comment by houseoftheed** [comment]
I'm not encountering these issues with the latest release, thanks!

**Comment by klaritan** [comment]
The NeoGeo core has been running and being played over the course of last 12 hours and my MiSTer has not experienced this yet. Great work, thanks!

**Comment by Shogun7797** [comment]
Just played for about an hour and it seems to be fixed.  Thanks!

**Comment by klaritan** [comment]
Since everybody with the old issue confirmed that it's no longer present with sorg's latest update (20191116), I'll close this issue. If I ever experience this again, I'll reopen it.

Thanks Sorg, again, for fixing this so quick.

**Comment by jotego** [comment]
How was this fixed then? Was it related to DDR3 then?

**Comment by sorgelig** [comment]
Reverted changes in jt49_cen fixed the issue.

**Comment by jotego** [comment]
Thank you. So there must be something odd there after all.
