### ISSUE TITLE
Harsh chime sound in Money Puzzle Exchanger

### ISSUE THREAD

**Issue by raygan** [MiSTer-devel/NeoGeo_MiSTer#56]
Money Puzzle Exchanger plays a chime sound whenever you place a coin (so essentially constantly, as you're usually doing that once a second or so while playing.) On MiSTer, this sound is noticeably louder and shriller than on actual hardware. It's pretty obvious, and kind of painful to listen to! Boot up the game in any mode and you'll notice it right away.

I don't have a good capture setup to provide a recording, but I I've compared this to my actual MVS and the difference is very obvious.

**Comment by M-Walrus** [comment]
This issue was fixed a long time ago and should be closed. It does not still occur in the most recent core.
