### ISSUE TITLE
Garou Mark of the Wolves logic/graphic issue

### ISSUE THREAD

**Issue by kimbapslice** [MiSTer-devel/NeoGeo_MiSTer#57]
In Garou Mark of the Wolves during Hotaru Futaba's bell stage, the pigeons flying down in a line clump up on the ground instead of spreading out as in real hardware. Using 128MB RAM from MisterAddons.

**Comment by rsn8887** [comment]
I see the same effect.

**Comment by raygan** [comment]
I'm seeing this as well. It's pretty funny but obviously incorrect. Using the 19.12.5 build and the 128mb ram module from MiSTerAddons.

**Comment by Kitrinx** [comment]
This should now be resolved.

**Comment by kimbapslice** [comment]
Thank you! I will eagerly await the chance to check this out when the new build arrives!

**Comment by Chocobobobo** [comment]
Just checked it on the latest build (20200123) and no more pidgeons from the Matrix. Bug fixed.

**Comment by kimbapslice** [comment]
Pigeons are flying in normal again! Case closed! thank you so much!
