### ISSUE TITLE
Latest update sometimes dispalys permanent black screen 

### ISSUE THREAD

**Issue by klaritan** [MiSTer-devel/NeoGeo_MiSTer#58]
On 20191125, sometimes NeoGeo can go black screen on booting the core and never recovers. Audio & gameplay seems to be ok.

This happened to me a few times, but it's random. Boot straight to NeoGeo. No core switches.

**Comment by LeKrang** [comment]
Hi,

I have the same issue. But on my end it seems to be only for NTSC mode.
When I manage to get it to boot without a black screen (around once out of ten times) if I switch to PAL then it plays fine and boots normally every single time.
Switching back to NTSC reintroduces the issue.

**Comment by M-Walrus** [comment]
This issue report is almost a year old, and there are no recent reports of any behavior like this.

Seems this ticket should be closed.
