### ISSUE TITLE
Latest update (20191125) : displays random flash screen (sometimes continuous)

### ISSUE THREAD

**Issue by steffpga** [MiSTer-devel/NeoGeo_MiSTer#59]
Hi,

Since the last update, i have random flash/twinkle in total screen in game...(console or arcade mode)
It's the first time i met this problem....
I test for alpha mission 2, fatal fury 2 or samourai showdown.
For information : i have a 128MB SDram

**Comment by tonurics** [comment]
I am experiencing the same problem with release 20191125 [128MB RAM as well]. Screen blanking with video dropout happens at random, usually after a couple of seconds. Issue starts on the core menu screen [before loading a game] and persists once a game is loaded.

I haven't done extensive testing, but 20191116 appears to work normally.

**Comment by steffpga** [comment]
@ tonurics 
Yes, i have me too screen blanking with video dropout happens at random, usually after a couple of seconds.
I try to delete all neogeo config files and restart the core but it produce the same effects with all games i launch...
The November 16th as not this issue...all is fine with it, works normally
I saw on the net that some have these problemes with the 20191125 release.

**Comment by sorgelig** [comment]
try this build:
[NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/3902664/NeoGeo.zip)

**Comment by steffpga** [comment]
Hi sorgelig,

First, i wish to say you MERCI for your reactivity !
I'm going to test this build and all is OK with it !
The screen blanking with video dropout happens at random which occured aren't present in this version !
**All is OK !**

The + of this build is the arcade selection is apparently good too. Before, i can't launch games with many ram in arcade mode and now it's OK !

A big thanks for you and Gratitude fot all you make for pfga model ! What a pleasure to play theses consoles like before, in the same conditions !

**Comment by Techsteps** [comment]
> try this build:
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/3902664/NeoGeo.zip)

sorgelig: This is the only version that has worked for me. None of the last three releases (116 to latest) have done anything but show black blank screens that I cannot reset or osd out of. 

Also do the games HAVE to be in a seperate games folder from bios? Seems it boots more consistently when they are, but thought it was only cosmetic.

**Comment by esmith13** [comment]
> try this build:
> [NeoGeo.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/3902664/NeoGeo.zip)

@sorgelig 
Same as above. As of Jan.28, 2020 only your build posted here works with 128MB ram installed. My 32MB module works with all releases of NeoGeo but the 128MB from MiSTerAddons.com ONLY works with your testing build here. When using a current build with the 128MB ram, all lights on I/O board 5.5 go out - including optical audio LED. MiSTer becomes completely unresponsive to keyboard, wired controller and even buttons on I/O board.
