### ISSUE TITLE
Odd sounding pitch during music in different games

### ISSUE THREAD

**Issue by kimbapslice** [MiSTer-devel/NeoGeo_MiSTer#60]
In several games, the music sounds a bit off.

For example:
In Garou Mark of the Wolves during Hotaru Futaba's giant bell/church rooftop stage, the music sounds like a bad VHS tape with audio warble. The flute instrument sound.

I have noticed this in games like Samurai Shodown 3 as well in different stages/character songs like Rimururu or Nakoruru's. This game has a great soundtrack.

Last Blade: Select Yuki and the first fight will be Amano at the bridge cherry blossom stage, the music is affected.

I will try to list more games and examples, but Garou is definitely noticeable and reproducible. It's hardly game breaking. Thank-you! I am running the newest release 11/25/2019 with 128MB RAM.

**Comment by MonokromFR** [comment]
Hi. heard the same here.
- Blazing Star stage 2 soundtrack, when higher synth samples (at the end of the loop), looks like wierd drunked tone/pitch music.
- FF3 (0x072F music code - Terry stage) also have.

running last avril neogeo core build

**Comment by MonokromFR** [comment]
Hi again
- Stakes Winner musics do the same. kind of "sounds" used in this game helps to really ear pitch issu.
IMO this is general issu, not for some games.
Hope next release will fix it.

on the other hand (i don't want to add another thread with sound issu):
- on Metal Slug X, stage 2, second part: there are missing half xylophone's notes (code 0x0023)

running:
MiSTer v200429 / NEOGEO v200510
IO board analog out (direct out) / 128Mo ram

thanks a LOT all of you for amazing work!

**Comment by jotego** [comment]
Hi, this is the author of JT12, which was forked on this repository to handle the sound. If you can produce VGM files of the relevant music tracks where the problem occurs I will check if the problem is in JT12. Thank you.

**Comment by MonokromFR** [comment]
Hi there Jotego ;)

here are 3 VGM:
Blazing Star - Stage 2
FF3 - Terry song
Garou - Happy ending
[NeoGeo-VMG.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4746081/NeoGeo-VMG.zip)

Thank you!

**Comment by MonokromFR** [comment]
and as i can't find VGM from Metal Slug X, there is records i done:
[Metal Slug X_xylophone.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4746150/Metal.Slug.X_xylophone.zip)
0'0" to 0'15" is original
0'15" to 0'30" is from MiSTer

Thank you!

**Comment by jotego** [comment]
Hi @MonokromFR,

I have simulated the VGM files. Blazing Star [blazing.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4780767/blazing.zip)
and FF3 [FF3.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4780768/FF3.zip) sound ok to me but I have just fixed one issue (https://github.com/jotego/jt12/issues/57) that may have been causing problems here too.

But I do hear some noise in [GAROU.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4780769/GAROU.zip), around secons 8-10 there is a rythmic pattern in channels coming from ADPCM-A module.
[GAROU_adpcmA.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4780783/GAROU_adpcmA.zip). Is that what you were referring to? 
(For reference: the track [is here](https://vgmrips.net/packs/pack/garou-mark-of-the-wolves-neo-geo), number 30)

**Comment by MonokromFR** [comment]
Hi Jotego

thanks for reply!

there is my feed back about your sample above:
- Blazing star: sounds good to me.
- FF3: your sample sounds horrible to me and don't match original hardware at all.
- Garou: this is the right song i was talking about (#30), but same issue as FF3 to me. also, GAROU_adpcmA don't meet instrument i was talking about.


Issues @kimbapslice and I were talking about are not glitches or rythmic pattern, we would say "bad VHS tape with audio warble" or "wierd drunked tone/pitch". or same like a vinyl turntable with bad belt.

Pay close attention to FF3 sample: forget about guitar and drum, listen to the 3th synth note:
MV2F seem higher and regular, MiSTer seems lower and drunked.
[FF3_3th_note.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4783145/FF3_3th_note.zip)

Pay close attention to Blazing Star: on MiSTer record i made a (A) shot at 0"4' that affect music.
[BlazStar_Get_ready.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4783149/BlazStar_Get_ready.zip)

There is an BlazingStar in game record. listen to MiSTer record:
- i made a (A) shot at 0"9'
- (B) shot at 0'11" then enemy explose: music is wierd.
(you can listen to MV2F in game record but this is of course not the same shot at same moments).
[BlazStar_IN_GAME.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4783151/BlazStar_IN_GAME.zip)


I think:
- playing soundtrack from jukebox player with Unibios doesn't reveal too much odd sound issue.
- listening IN GAME seems to be very more revealent and comes randomly. Maybe there is a link when others sounds are played at the same time?

I played Blazing Star a lot a few years ago and music is stuck in my head, I noticed this issu the first time i played it on MiSTer.

Thanks to trying to figure it out, i hope my explanation are clear enough, it is hard to explain sound by writing (and obviously my english is crappy).

PS: records sounds are very different, MiSTer is crystal clear while MV2F contains less trebles. the point isn't here :)

**Comment by kimbapslice** [comment]
Sorry I haven't had much time to test recently either, but the last few play times I did get in the latest versions, the warbly-ness of the audio seemed to have decreased a lot. I will try to sit down and track down more specific instances. Will update.

**Comment by jotego** [comment]
That's a lot of information, @MonokromFR. Thank you.

I was working with some old files. After replacing them I think FF3 and Garou will sound ok to you. Please let me know what you think about them now:
[FF3-17 Garou-30.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/4785534/FF3-17.Garou-30.zip)

About the pitch movement in the Blazing Star in-game recording: Yes, I can hear that between seconds 11 and 12 there is one instrument whose pitch drifts away. But I cannot debug that. I can only debug using VGM files for reference. Once the sound module goes into the rest of the system and we compile it into the FPGA, debugging becomes extremely hard. Please let us focus only at problems we can reproduce with VGM files.

**Comment by MonokromFR** [comment]
Hi Jotego.
Your last FF3 rip sounds bugged to me, while Garou seems ok now...

I'm not a dev at all and trying to understand what you say ;)
I just pointed out what i hear at final analog output: tracks are impacted by others tracks/SFX played at the same time.
You know better than me what could be wrong ;)

**Comment by kimbapslice** [comment]
Hello,

Sorry for the slowness on my part. I got out my AES and a NeoSD Pro and loaded up Garou Mark of the Wolves (I also have Garou in MVS if you need me to try). Using the Mister 6-22-2020 build of Neogeo with all Mister files updated.

In Garou Mark of the Wolves:
Mister 6-22-2020 build
System Type: AES, Bios: Unibios (4.0), Video Mode NTSC
In the Unibios Menu JukeBox Music Player, use sound code 0x072A (unknown music) and 0x734 (Hotaru)

They both sound really bad when the flute sample plays.

Compared this to the real AES and it's day and night. I tried to record it on my phone and the sound quality is not good for sharing. I am certain this bug is in other games.

**Comment by jotego** [comment]
Hi @kimbapslice,

Thank you for your detailed report and sorry for insisting but it does save me a lot of time if I can be pointed directly to a VGM file of the melody in question.

I think the last sound fix I made has not been yet released by MiSTer curators. But if you're talking about sample music it won't be affeced by it as it was related to PSG.

Thank you

**Comment by kimbapslice** [comment]
Hello @jotego ,

Sorry I misread your last comment and overlooked the request for VGM files (I didn't know what these were - VGM). Anyway, attached are the 2 VGM in question for Garou Mark of the Wolves and verified still glitch exists in Neogeo build 8-20-2020

In Garou Mark of the Wolves:
Mister v200814, OS v200618, Neogeo 6-22-2020 build
System Type: AES, Bios: Unibios (4.0), Video Mode NTSC
In the Unibios Menu JukeBox Music Player, use sound code 0x072A (unknown music) and 0x734 (Hotaru)
I downloaded the vgms from vgmrips.net
[garou vgms.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/5160374/garou.vgms.zip)

**Comment by Bocop** [comment]
> Hi @kimbapslice,
> 
> Thank you for your detailed report and sorry for insisting but it does save me a lot of time if I can be pointed directly to a VGM file of the melody in question.
> 
> I think the last sound fix I made has not been yet released by MiSTer curators. But if you're talking about sample music it won't be affeced by it as it was related to PSG.
> 
> Thank you
It's really noticeable during the title music for Pulstar as well, about 30 seconds in after loading the game once the gameplay demo starts and there is action on-screen (shots being fired, ships exploding, etc.). The music speed and pitch really starts dragging as though it's being played back on an analog reel-to-reel player with a dirty head.

It doesn't exhibit this behavior when played back in the game's Options screen in AES mode.

**Comment by jotego** [comment]
If it does not occur when played via the menu, it is likely to be a bus contention issue unrelated with the YM2610 implementation. 
Commands or PCM data to the audio "chip" must be coming in late.

**Comment by Bocop** [comment]
Anything new on this? seems unresolved.

**Comment by Dubon77** [comment]
@furrtek did a decap of the PCM chip so that might provide some insight

**Comment by stainmage** [comment]
Hello same problem here but I noticed the pitch variation in every game I tested : Art of Fighting, Kof98, Snk vs Capcom...

Here is a comparison between the core and a real neo geo

https://drive.google.com/file/d/1szaYSXKVfdZ9bnq_-mSRIFflALAyzSgA/view?usp=drivesdk

https://drive.google.com/file/d/1sqCVhe7P5jOVbZtC4V_RC36oJ95ZnUSW/view?usp=drivesdk

You can sense after pressing the start button how the second note drifts away in some kind of modulation while the computer shows the tutorial.

There are many parts of the game that has the same problem.

Cheers

**Comment by stainmage** [comment]
Hello, I've notice the pitch problem in all games I tried.

i can remember for sure Kof98, SNK vs Capcom, Art of fighting.

Here's a comparison between original cartridge sound and from the core today

**Comment by kimbapslice** [comment]
I am trying out the new 09/08/2021 neogeo core update:
NeoGeo:
- Audio fixes (greyrogue)
- Reduce SDRAM cycles (fixes KOF'94 and some other games graphics glitches).

Seems like the pitch variation is gone!!! Amazing work! So far I have only tested Samurai Shodown 3 and Garou Motw. Please someone confirm and we get to close out another bug. Thanks greyrogue and everyone for making this core better everyday!

**Comment by kimbapslice** [comment]
I have been testing a few additional games and they all sounded very good! Closing ticket!
