### ISSUE TITLE
Full MVS library bug report

### ISSUE THREAD

**Issue by black-francis** [MiSTer-devel/NeoGeo_MiSTer#65]
All tests were done with NeoGeo_20191205.rbf and the darksoft rom set with the stock bios. 

All results compared against footage of real hardware where available and MAME to check that what is being seen on the core is not present elsewhere.

_**SPRITE ERRORS**_ 
sprites either missing, staying on screen too long or misplaced

world heroes perfect- chunk of sprite missing in intro
https://i.imgur.com/c1vUh8D.jpg

real bout fatal fury- sprite stays on screen in intro
https://i.imgur.com/YIhNTCe.jpg
 
king of the monsters- diagonals on joystick sprite shifted.
https://i.imgur.com/idWnT7P.jpg

kof 2002- sprite stays on screen, overlapped by new sprites when they appear.
https://i.imgur.com/8S8WbR6.jpg

power spikes 2- sprite lingers on screen in intro, too fast to capture.

_**HORIZONTAL SHIFT / VERTICAL LINES**_
areas where sprites are a pixel to the left or right of where they should be. areas on the left side of the screen or sprite where a vertical line is present, can be either solid coloured, shows the background layer or seems to mirror the right most side of whatever is being shown. have not stated that sprites are left or right of where they should be as I don't know which part of the screen is actually causing the misalignment

2020-baseball- green vertical line on left of screen.
https://i.imgur.com/jetjdIX.jpg

aero fighters 2- circled vertical line in intro. vertical line of left of screen.
https://i.imgur.com/1z5I6lJ.jpg
https://i.imgur.com/DOl2B51.jpg

aggressors of dark combat- health gauge and border not aligned properly.
https://i.imgur.com/1j6t5es.jpg

chibi marukocham deluxe quiz- grey vertical line on left of title screen
https://i.imgur.com/hgUZSZu.jpg

baseball stars 2- "1p" selection box and possible other assets shifted
https://i.imgur.com/yKLeN6z.jpg

garou mark of the wolves- several vertical lines on left side in intro. misshapen boxes in second attract sequence. main character portraits in character select screen shifted.
https://i.imgur.com/Tbwmfe1.jpg
https://i.imgur.com/WbDsE5B.jpg
https://i.imgur.com/Z52jDUp.jpg

kof 94- character portraits shifted
https://i.imgur.com/ceMWlcI.jpg

kof 95-character portraits shifted
https://i.imgur.com/6RTC3MZ.jpg

kof 96-"in oaska" stage intro horizontal line.
https://i.imgur.com/ViZjPNq.jpg

kof 97- character portraits and border shifted, goes into overscan area
https://i.imgur.com/OnBpyXm.jpg
https://i.imgur.com/SufiwH2.jpg

kof 98- circled green line in intro
https://i.imgur.com/5K7atNP.jpg

kof 99- health bar and character portrait shifted
https://i.imgur.com/sMu7eVE.jpg
https://i.imgur.com/ode0eoV.jpg

kof 2001- character portrait spacing. vertical line of left of screen.
https://i.imgur.com/TibH6vA.jpg
https://i.imgur.com/6deAY95.jpg

kof 2002- character portraits shifted
https://i.imgur.com/1bvucOC.jpg

kof 2003- grey vertical line of left of screen.
https://i.imgur.com/oNJctiH.jpg

king of the monsters- vertical lines on character select screen.
https://i.imgur.com/idWnT7P.jpg

king of the monsters 2- vertical lines on character select screen
https://i.imgur.com/aTMOWEg.jpg

kizuna encounter- vertical line in intro
https://i.imgur.com/sOLId4u.jpg

last blade 2- line not straight in intro
https://i.imgur.com/9yODgvp.jpg

magical drop 3- blue vertical line of left of screen.
https://i.imgur.com/v7FfmhE.jpg

matrimelee- shifted character portraits
https://i.imgur.com/q02Go6V.jpg

metal slug- vertical line of left of screen.
https://i.imgur.com/VPOvAnm.jpg

money puzzle exchanger-  vertical line of left of screen.
https://i.imgur.com/DwQ85XN.jpg

neo turf masters- lines in shot bars, vertical line of left of screen.
https://i.imgur.com/HWslVwe.jpg
https://i.imgur.com/2LvDH86.jpg
https://i.imgur.com/zWKUGh5.jpg

puzzle de pon- grey line left of screen in intro.
https://i.imgur.com/ldfODyb.jpg

rage of the dragons- character portrait spacing, left side clipped
https://i.imgur.com/WfLx4rp.jpg

ragnagard- character portrait border incorrect
https://i.imgur.com/zW2WRhj.jpg

real bout fatal fury special- vertical line of left of screen.
https://i.imgur.com/AHTWogB.jpg

real bout fatal fury special 2- character portrait spacing
https://i.imgur.com/sR8uyPM.jpg

riding hero- see screenshots.
https://i.imgur.com/h12AGx3.jpg
https://i.imgur.com/sRHacOL.jpg
https://i.imgur.com/EqiBcP8.jpg 

samurai showdown v- 304 res shows shifted border to right, clipping right side of screen and showing extra line on left side.
https://i.imgur.com/S56YIhS.jpg
https://i.imgur.com/XDDSm8b.jpg

samurai showdown v special- see above but with character portrait border between matches
https://i.imgur.com/9YMCTAj.jpg

snk vs capcom- intro lines, see pics.
https://i.imgur.com/j12gRqC.jpg
https://i.imgur.com/JtX9Cqc.jpg
https://i.imgur.com/E4kN8WQ.jpg

soccer brawl-  "select field" box one pixel to right
https://i.imgur.com/PY5ww3m.jpg

spin master- lines left on screen in intro and gameplay, flickering so hard to photo.

street hoops- character selection spacing
https://i.imgur.com/s5JGe0r.jpg

strikers- variable left side border black line, can be cut into by enemy sprites
https://i.imgur.com/SUvfCtv.jpg

super sidekicks 2- screen spacing
https://i.imgur.com/e2wJdni.jpg
https://i.imgur.com/RMIjgk2.jpg

top layers golf- vertical line of left of screen in intro
https://i.imgur.com/gbGb0qV.jpg

twinkle star sprites- see screenshot
https://i.imgur.com/XFPRoN5.jpg

ultimate 11- title screen one pixel to left
https://i.imgur.com/ALdHjAA.jpg

voltage fighter gowcaizer- character select screen spacing. line on left side.
https://i.imgur.com/zmacngz.jpg
https://i.imgur.com/SBXHVaK.jpg

waku waku 7- various vertical lines on left hand side
https://i.imgur.com/yNt2dNB.jpg
https://i.imgur.com/s5cuEdo.jpg
https://i.imgur.com/5RyQhKj.jpg
https://i.imgur.com/YjYK7Rh.jpg

wind jammers- vertical line of left of screen during play. line in intro, too fast to photo.
https://i.imgur.com/R5DzvUn.jpg

world heroes 2- character portrait shift
https://i.imgur.com/87burP3.jpg

world heroes 2 jet- character portrait shift
https://i.imgur.com/ZtuvkAl.jpg

world heroes perfect- character portrait shift. circled vertical line in speech box.
https://i.imgur.com/BPSj8Lc.jpg
https://i.imgur.com/XVbaHzC.jpg

zupappa- vertical line of left of screen during playsee screen
https://i.imgur.com/EX4GdxF.jpg

_**AUDIO**_
needs further investigation against real hardware

art of fighting 2- right side audio grindy sounding?
sengoku 3- audio very crackly in character selection?
snk vs capcom- generally hissy audio?

_**FLICKERING**_
these games show flickering white dots between screen transitions eg going from in game to a continue screen or going from the title screen to the character select screen.

power spikes 2
pulstar
riding hero
real bout fatal fury special
soccer brawl
stakes winner
stakes winner 2
street hoops
super spy
ghost pilots
mutation nation

2020 baseball- many flickering horizontal lines during spinning "2020" logo in intro 

tecmo world soccer- horizontal flicker on cross bar in intro

kof 2000- flickering white dots at the top of the screen when going to main title screen

kof 2001- flickering white dots at the top of the screen when going to main title screen

last resort- background flickering when shooting enemies, really noticeable in tunnel of first stage. real hardware and mame do not exhibit anywhere near as much flickering.

baseball stars 2- quick black horizontal line across first white screen in intro after bios screen

blazing star- flickering white dots at the top of the screen when going to main title screen. also has general flickering between screen transitions

ninja commando- large amount of sprite flickering and shaking on logo during attract sequence. ground tearing during gameplay. real hardware and mame do not seem to exhibit anywhere near as much flickering in below areas pictured.
https://i.imgur.com/L5CZdt8.jpg
https://i.imgur.com/dYmBfGs.jpg

metal slug 4- sprites flickering in and out of foreground first stage. real hardware and mame do not seem to exhibit anywhere near as much flickering. see bottom right in picture.
https://i.imgur.com/Qu7Yyuc.jpg

top hunter- general flickering of pixels at top of screen, present in real hardware but seems less prevalent.

**Comment by sorgelig** [comment]
There is one thing probably you miss:
While screen is 320px, most games are 304px while 8px on each side are considered outside of visible area. This is why core provides OSD option 304px. 
Basically you need to set 304px to simulate visibility of real console.

**Comment by black-francis** [comment]
im well aware of that but even in 304 there are vertical lines appearing where they shouldn't be and misalignement. many of these lines are appearing way inside the 304 area too. in quite a few games it was obvious that they were meant to be displayed in 304 so I didn't even add them to the list. you can set mame to 320 for any of these games and see that the vertical lines are not there in the image, character portarits, hud etc are all perfectly centered.

i even show this in the two samurai showdown v screens, the image is right shifted, showing a vertical line on the left side even when set to 304, the core is getting something wrong.

**Comment by rsn8887** [comment]
I am not sure if this is related but in Pulstar I noticed stationary enemy sprites were sometimes shifted a pixel away from the background where they should be, and that the shift depended on the scrolling. It looked as if the sprite movement was not synced perfectly with the background scrolling.

**Comment by black-francis** [comment]
samurai showdown 4- missing section in intro is over a larger area than real hardware. health bar alignment is i.
![IMG_5092](https://user-images.githubusercontent.com/44230562/71134634-e6701d00-21f6-11ea-96b6-185a9943e8c9.JPG)

**Comment by Dubon77** [comment]
Thank you for testing this, im sure it will be very usefull once furrtek gets some time to look at the bugs

**Comment by steffpga** [comment]
Force to recognize that these sprite errors, horizontal shofts / vertical lines etc are a reality compared to real Neogeo system...

the question is : why these issues exist in a FPGA configuartion?

**Comment by jotego** [comment]
Because bugs exist. We have typos when we write, sometimes we intend to write something yet write something else, sometimes we think we understand something and write the code accordingly but we didn’t... 
There are things that just work differently because of the different technology used. Particularly the use of one modern RAM memory instead of a large bank of parallel ROM memories. And that interface may be a source of errors until it gets polished.

**Comment by steffpga** [comment]
OK jotego ! ;)
NeoGeo core is one of the most attractive console core !
These bugs exist but they aren't harmful to play in superb conditions, playing in very good conditions compared to emulation....
This core is young and we hope these bugs are solved in the future ! ;)

**Comment by theypsilon** [comment]
Just for adding another source to one case of this report:

> aero fighters 2- circled vertical line in intro. vertical line of left of screen.
> https://i.imgur.com/1z5I6lJ.jpg

Here is a video, it happens in second 29. Tested with 200325 release.
https://www.youtube.com/watch?v=N1iraPRtBCo&t=29s

**Comment by furrtek** [comment]
Most of the issues related to the sprite layer / fix layer shift bug (vertical lines, gfx 1 pixel outside of borders...) should be fixed with 77a2a8e516ac75d3afb46d85ce70faa5dcc21a99.
Thanks for reporting :)

**Comment by Chocobobobo** [comment]
Hey blackfrancis, any chance to check if the issues you found were fixed with the latest version of the core? Thanks!

**Comment by ItsAtomico** [comment]
Pulstar: FWIW the fast flickering lines of garbage displayed right in the middle of the screen after transitions are still there. 

Just credit up, hit start and there they are. And again after the how to play screen. And after level select. 

Sorry I can't add a screenshot, the print screen method on my keyboard's unnecesarily complicated lol

There's also some weird lines on the upper few lines of the monitor when an explosion fills the screen (e.g. destroying the first bigger that appears early in level 1). Not sure if that's just standard neo geo overscan garbage, tho.

**Comment by asturur** [comment]
I was playing today:
- far east of eden zero, and i noticed that before the battle at the vs screen, the right character covers the VS logo
- metal slug 5 the water ripple made by the canoe are over the contiue count

**Comment by birdybro** [comment]
[NeoGeo_SpriteHack_20220212.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/8074935/NeoGeo_SpriteHack_20220212.zip)

@black-francis can you please test these with @greyrogue 's latest test build? It should fix some of these.

Thanks!

**Comment by paulb-nl** [comment]
This issue can be closed. Most of the reported issues here are fixed.

The reported white dots during transitions are normal for Neo Geo hardware as can be seen in these videos:
Pulstar: https://youtu.be/uhDr5Y098cw
Blazing star: https://youtu.be/pdozCZ4SIvw

If there are still issues then separate issues can be opened.

**Comment by wwark** [comment]
Hi @paulb-nl,
I tried the fix of Ninja Commando for flickering with neo file and darksoft file but the flickering confinue on the logo of the game during the atrac mode.
Is your fix is also for this part ?
Thanks for your time :+1:

**Comment by paulb-nl** [comment]
No the logo part is also flickering on real hardware. Check this video: https://youtu.be/80GG41vJIGA?t=37

The flickering which is fixed happened after choosing the difficulty.
https://i.imgur.com/dYmBfGs.jpg

**Comment by wwark** [comment]
Ok thank you !
