### ISSUE TITLE
Garou Mark of the Wolf - Issue with the random

### ISSUE THREAD

**Issue by hoomlala** [MiSTer-devel/NeoGeo_MiSTer#68]
- When we play on Story Mode, we select a character and we fight with always the same opponent
Eg :  Each time i select Rock my first opponent is always Hotaru 

- In Versus Mode, I choose the random stage so the stage suppose to be random => we play with always the same stage (Hotaru Stage)

**Comment by sqwirral** [comment]
Possibly fixed a while ago but not yet in the latest build, see https://github.com/MiSTer-devel/NeoGeo_MiSTer/pull/66

**Comment by evanclarke** [comment]
Another place I noticed this was the birds in the background of the stage in the bell tower.  The birds all fly in the same path and land on top of each other.

I'll check if it's fixed when the latest build mentioned is released.

**Comment by vpelletier** [comment]
20200123 has been released with the fix, could you try to reproduce with this version ?

**Comment by hoomlala** [comment]
Work Perfectly Thanks
