### ISSUE TITLE
Loading Neo Geo core without loading Menu core first

### ISSUE THREAD

**Issue by sqwirral** [MiSTer-devel/NeoGeo_MiSTer#69]
If you have a bootcore set in the Mister ini, then it's possible to load Neo Geo without ever loading the menu first. If you do this, you get 'Not enough memory!' errors for every game you load, along with other issues such as Z80 ERROR (at least on the Japanese MVS BIOS I have installed).

The workaround is to reboot to the Menu core first before loading the Neo Geo core.

**Comment by sorgelig** [comment]
It's not workaround. This is the way MiSTer meant to be used.
