### ISSUE TITLE
romset entries for gog.com releases ?

### ISSUE THREAD

**Issue by vpelletier** [MiSTer-devel/NeoGeo_MiSTer#70]
I have purchased a few of the NeoGeo games available from gog.com (though so far limited to the games which work with 32MB SDRAM). In at least the Linux installer of each of these games were all the files needed to start playing (apparently accessibility may vary by game and/or platform).

I could come up with romset entries for the following:
- fatfursp
- fatfurspa
- ironclad
- ironclado
- kotm
- kotmh
- mslug
- mslug2
- mslug2t (by patching GOG's roms)
- samsho2
- samsho2k
- samsho2k2
- twinspri

I did a minimal test of most (checking graphics & sound are consistent until in-game, and checking program rom CRC from UniBIOS), and play-tested mslug, mslug2 and mslug2t to the end credits.

Is there a way for me to contribute these back without breaking existing setups ? Especially, game variants would need separate entries, and I am not too comfortable with giving non-"standard" name to each game...

Maybe by extending romsets syntax to allow specifying alternative file sets, and the loader deciding which one it should pick based on which files are actually present ?

**Comment by sorgelig** [comment]
MiSTer supports several extra features:
1) romset.xml per game folder folder like fatfursp/romset.xml  the format is the same, just <romset> .. </romset> clause is the root in xml.
2) romsets.xml per folder with game folders. So you can make a subfolder with gog games and use specific to gog romsets.xml

probably second option will be more conveneient. You can make PR with gog-romsets.xml and in readme we can explain how to use it.

**Comment by vpelletier** [comment]
With #71 merged, I believe this can be closed.
