### ISSUE TITLE
KOF 94 Japanese flickering text

### ISSUE THREAD

**Issue by Chocobobobo** [MiSTer-devel/NeoGeo_MiSTer#73]
I didn't see a lot of love for the games played in Japanese, so here we go:
The right part of the text after a match will flicker.

Hopefully Furrtek can do some magic after having fun with his Neo CD current madness.
![20200214_000949-screen](https://user-images.githubusercontent.com/23947970/74486900-6a284c00-4ebe-11ea-971e-0d36cf3a462b.png)

**Comment by BrendleFly** [comment]
I can confirm that this is also happens when language is set to English.

**Comment by farhanjiwani** [comment]
+1 for both posts above

**Comment by furrtek** [comment]
The same issue appears on my setup. Might be related to #26 . Currently investigating.

**Comment by wwark** [comment]
Maybe another case to those issues, in metal slug 5, there are graphical issues on the countdown of continues in the background is in motion.

**Comment by Chocobobobo** [comment]
Hey Furrtek, any progress, discovery on this one? Just saw you found something related to PCM chip... Fingers crossed.

**Comment by mikey1964** [comment]
this bug has been fix its the same bug as  Kof94 Graphics Glitches All Over The Place #110 can you guys check 

tutifrutas "I tracked it down to this commit b4f924d if I get latest from master, revert this commit and build the core the graphic glitches are gone."

compiled core https://github.com/tutifrutas/NeoGeo_MiSTer/blob/master/releases/NeoGeoKof94_20210905.rbf

**Comment by mikey1964** [comment]
this issued has been fix can you guys recheck and close it

**Comment by farhanjiwani** [comment]
Confirmed! I don't see the issue any more :)
Thanks!!
