### ISSUE TITLE
Period in game name cuts off title in OSD

### ISSUE THREAD

**Issue by elfbutt** [MiSTer-devel/NeoGeo_MiSTer#76]
If the altname in an entry in the romsets.xml contains a period ".", the OSD will stop displaying the name there. In the current romsets.xml there is already a game named "Neo Mr. Do!", this shows up as just "Neo Mr". But you can test by adding a period to any other game's name and see it happening.

**Comment by Toryalai1** [comment]
I just checked and for me I can see that it says Neo Mr. Do!

**Comment by sorgelig** [comment]
yeah. it was fixed some time ago.
