### ISSUE TITLE
KOF 98 - Stage Camera Failure

### ISSUE THREAD

**Issue by tacodaemon** [MiSTer-devel/NeoGeo_MiSTer#78]
The "camera" occasionally fails to follow characters as they move around the stage. Characters can move far out of view of the player while the camera remains static. I tried to reproduce this in AES practice mode, but couldn't after several stage changes. I was only able to reproduce the problem twice. Here are the specifics I can provide:

Miser v200216
NEOGEO v200123
Default Settings

- Started Arcade Game
- Chose Advanced mode (Default) and Terry, Andy, and Joe as my team.
- Chose same order to fight with.
- Fought on Korea Stage.
- Won all three rounds with Terry without taking a loss.
- Chose same team order for 2nd round. This was the China stage on the first try, and Japan stage on the 2nd try.
-Camera does not follow character action.

I tried a third time with the same steps, but lost with Terry and my character changed to Andy. The 2nd stage was the Middle East, and the problem did not occur.

**Comment by Kitrinx** [comment]
Can you verify that the rom you are using has been patched to remove the copy protection? Darksoft are by default.

**Comment by Toryalai1** [comment]
I didn’t manage to get Korea stage, despite doing what you wrote. Can you still reproduce the error with paulb-nls latest commits?

**Comment by tacodaemon** [comment]
Wow, I forgot about this. I guess I haven't played that much of Kof98 since! I just played 3 stages, ending with 5 rounds of the Korea stage. Same ROMs as before, but no problems. I assume this was fixed sometime in the last 3 years.

**Comment by Toryalai1** [comment]
Great. Please close :)
