### ISSUE TITLE
Corrupted graphics in AOF3 credits

### ISSUE THREAD

**Issue by Chocobobobo** [MiSTer-devel/NeoGeo_MiSTer#80]
Checked on JPN MVS version.
![20200308_175230-screen](https://user-images.githubusercontent.com/23947970/76167366-5fcc3b80-6166-11ea-9179-e3f2bc344dcb.png)

**Comment by Toryalai1** [comment]
This is not happening with original BIOS. Maybe someone can check with real hardware that has unibios

**Comment by Toryalai1** [comment]
This is from real hardware with unibios 4
https://media.discordapp.net/attachments/788351725512949770/1133880770809843762/PXL_20230628_075336608.mp4

**Comment by Toryalai1** [comment]
This only happens if you enable cheats in unibios. I've confirmed it with another user that has a real hardware with unibios.

**Comment by sorgelig** [comment]
Not a MiSTer issue then
