### ISSUE TITLE
King of Fighters '94, The (GFX Issues)

### ISSUE THREAD

**Issue by BrendleFly** [MiSTer-devel/NeoGeo_MiSTer#81]
Game: King of Fighters '94, The (kof94).neo (from @MiSTer Pack Add-on - Neo Geo 2019-11-20.7z)

GFX glitch after the '8'
<img src="https://i.ibb.co/Nj53MPS/20200313-174207-screen.png" alt="20200313-174207-screen" border="0" />
GFX tiles appearing outside the game screen on these two:
<img src="https://i.ibb.co/dKcpKG1/20200313-174221-screen.png" alt="20200313-174221-screen" border="0" />
<img src="https://i.ibb.co/9Hyfj7L/20200313-174338-screen.png" alt="20200313-174338-screen" border="0" />
Right half of all win quotes flicker on and off:
<img src="https://i.ibb.co/Kwm5x8f/20200313-181329-screen.png" alt="20200313-181329-screen" border="0" />

- Info: MiSTer v200311, OS v200122, 128MB SD Ram.

- Neo-Geo Core v200123 (it says this when running the core, however, the file name is NeoGeo_20200123.rbf)
- System Type: Arcade (MVS)
- Bios: UniBIOS 3.3
- Video Mode: NTSC

- Memory Card: Plugged (this reverts back to plugged even if I save or reset)
- Auto Save: Off
- DIP Settings: Off
- Freeplay: On
- Freeze: Off
- Width: 320px
- Aspect Ratio: Original
- Scandoubler Fx: None
- Stereo Mix: None

I was unable to screenshot some others such as a glitch on a bird flying by in the England stage at the start, and a glitch once when character was hit. Cheers.

**Comment by farhanjiwani** [comment]
Having same issues.

Using HDMI output.
Latest UniBIOS

**Comment by furrtek** [comment]
Tiles appearing outside of the game screen may be normal. These columns were often cropped out by CRT displays so they may not be cleaned correctly. Will have to see if the game code does that deliberately or if it's a core bug.

The flickering quotes issue was reported in #73.

**Comment by sorgelig** [comment]
Many games needs 304px mode to be set. So it's normal if it displays garbage outside.
Since flickering is already mentioned in issue 73, i close this one as duplicate.
