### ISSUE TITLE
Sengoku 3 - Transition GFX Glitch

### ISSUE THREAD

**Issue by pseudobacon** [MiSTer-devel/NeoGeo_MiSTer#82]
There appears to be a problem with a number of rows of pixels at the top of the screen when transitioning to the next scene. Fading to black does not occur like the rest of the screen. Video of the issue:

https://streamable.com/5epyvy

**Comment by Toryalai1** [comment]
@pseudobacon, can you verify with the latest unstable build?

**Comment by Toryalai1** [comment]
I couldn’t see any glitches during transition

**Comment by pseudobacon** [comment]
I don't have access to a mister at the moment but basically the screen transition should be all at once to black. The top few rows were persisting. If there's no longer the case then it's fixed

**Comment by Toryalai1** [comment]
Yeah it was functioning normally. This ticket can be closed
