### ISSUE TITLE
Samurai Spirits 4 vibrant life bars

### ISSUE THREAD

**Issue by MonokromFR** [MiSTer-devel/NeoGeo_MiSTer#83]
Hi. I have seen the upper rectangle life bars's verticals lines are doubled than the original hardware is single line.
Issu happens when life bars are static. When a hard blow is done by fighter, bars are normally bouncing a couple of time but with no doubled line.

Thanks!

(using NEOGEO 20200325)
https://image.noelshack.com/fichiers/2020/16/4/1587067378-ss4-2.jpg

**Comment by furrtek** [comment]
Should be fixed with 77a2a8e516ac75d3afb46d85ce70faa5dcc21a99. Please close issue if confirmed.
Thanks for reporting :)

**Comment by sorgelig** [comment]
fixed
