### ISSUE TITLE
Far East of Eden: Kabuki Klash image errors

### ISSUE THREAD

**Issue by ThreepwoodLeBrush** [MiSTer-devel/NeoGeo_MiSTer#88]
Especially in the intro animation there are errors, like the face color layer (?) of a character missing.

**Comment by asturur** [comment]
At the vs screen the right player portrait is over the vs logo

**Comment by asturur** [comment]
I tested again the core after the recent update that fixes some graphical glitches, but those on this game are still there.

**Comment by paulb-nl** [comment]
Fixed in release 20221224
