### ISSUE TITLE
Line 94 has an extra /> anchor in romsets.xml 

### ISSUE THREAD

**Issue by MAME-GETTER** [MiSTer-devel/NeoGeo_MiSTer#90]
https://github.com/MiSTer-devel/NeoGeo_MiSTer/blob/master/releases/romsets.xml#L94

	`<romset name="nam1975" pcm="0" altname="NAM-1975" publisher="SNK" year="1990" vromb_offset="0x200000"/>/>`

**Comment by sorgelig** [comment]
thanks for info!
fixed.
