### ISSUE TITLE
Football Frenzy: Image offset issue

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/NeoGeo_MiSTer#93]
When scoring a touchdown, a graphic inside a box is shown of the losing team (which is fine), followed by the winning team - this image appears to be shifted to the left and the right fourth of it is missing in the box (solid color).

This can be reproduced with any combination of teams, any scoring team, with any region or BIOS type (AES/MVS/UNI).

I have reconverted a known-good ROM set from MAME 0.221 with NeoBuilder 1.06 and the issue persisted, so the problem is not with the ROM set.

**Comment by Toryalai1** [comment]
@rhester72 Can you please try this build:
[NeoGeo_unstable_20221208_158694.rbf.zip](https://github.com/MiSTer-devel/NeoGeo_MiSTer/files/10189599/NeoGeo_unstable_20221208_158694.rbf.zip)

**Comment by rhester72** [comment]
Confirmed as resolved!  Thank you!
