### ISSUE TITLE
Fatal Fury 3 - Error message upon loading

### ISSUE THREAD

**Issue by tenshin2002** [MiSTer-devel/NeoGeo_MiSTer#95]
I loaded Fatal Fury 3 and got an error message about memory and potentially bad contacts between cart and board.
After reset and apply from within core it booted fine. This happens everytime upon booting this game. Verified by other user on discord.
Using Darksoft rom with unibios 4.0. Other users with .neo files dont have this issue.

**Comment by sorgelig** [comment]
i cannot confirm.
Tried several times with UniBIOS and original BIOS in MVS and AES modes. Works fine.

**Comment by tenshin2002** [comment]
Did you test with Darksoft rom?

**Comment by sorgelig** [comment]
yea, darksoft

**Comment by wwark** [comment]
Do you have the same sha1sum (hash) for the zip file of Darksoft rom ?

**Comment by tenshin2002** [comment]
This issue is still present in latest current version of the core. Same memory error screen. After pressing reset and apply from the core menu and the rom loads.

**Comment by Kitrinx** [comment]
This game appears to need to initialize the memory once when used with unibios. After rebooting, be sure to save the ram and the memory error will not occur again.

**Comment by tenshin2002** [comment]
I just had some help from Rysha in the discord channel. I can now confirm that this bug happens if you have the core set to not autosave. It seems this game wants the memory to be initialized before boot. As soon as I changed the setting to autosave in the core and rebooted the game it worked without issues.
