### ISSUE TITLE
Last Blade 2 Sound Glitch

### ISSUE THREAD

**Issue by Manulegil** [MiSTer-devel/NeoGeo_MiSTer#96]
Hello,

I would like to report a sound bug I noticed in Last Blade 2 (great game btw). The game has been tested in AES version (japanese). I was able to compare with a genuine game on my AES.

In training mode, pick any character in speed mode, launch a custom mode (down down A or B) and as soon as you stop moving do it again, you will notice that the activation starts with no fx at all except for the voice.

**Comment by M-Walrus** [comment]
Most likely this is a duplicate issue of #75 - Sound FX and/or music cutting out or not playing.

I've copied the information from this ticket into #75 if this one can be closed out.

**Comment by Toryalai1** [comment]
I can’t recreate this

**Comment by Manulegil** [comment]
@Toryalai1 keep mashing the down down B or A input and you will notice that the activation only works one time out of two.

**Comment by paulb-nl** [comment]
The unstable build from yesterday contains the fix I did for this game: https://github.com/MiSTer-devel/NeoGeo_MiSTer/pull/175/commits/752b31c0c06a2765297d7a5519248f6327c02625

**Comment by Manulegil** [comment]
Solved
