### ISSUE TITLE
RAM not detected when core set to autoboot

### ISSUE THREAD

**Issue by Cwiiis** [MiSTer-devel/NeoGeo_MiSTer#98]
If you set the core to autoboot, it seems RAM isn't detected correctly? If I setup MiSTer to autoboot the last core, if it boots the neogeo core, it will complain about not enough RAM when loading any game (and of course there will also be graphical glitches) - if I disable autoboot and select the core manually, it works fine.

**Comment by sorgelig** [comment]
It's not a bug. 
MiSTer REQUIREs Menu to be loaded, even for a short time. 
There is autoboot feature where you can set 2 seconds delay to load the core you like.
